/**
 * IVX Deployment State Machine + Evidence-First Report Validator.
 *
 * Owner spec (2026-07-11): a deployment may ONLY be reported as VERIFIED when
 * every required evidence field is present, real, and consistent. Anything
 * less is UNVERIFIED — never a narrative.
 *
 * Steps enforced here:
 *  - Step 5: the only allowed states, in the only allowed order. No skipping.
 *  - Step 4/6: the 18 required evidence fields; forbidden template values
 *    (AUTO-GENERATED, UNKNOWN, PENDING, PLACEHOLDER, MOCK, NARRATIVE,
 *    GENERATED, SIMULATED, ESTIMATED, ASSUMED) invalidate the report.
 *  - Step 7: health endpoint must be HTTP 200 AND the running commit SHA must
 *    equal the GitHub commit SHA (short-SHA prefix match allowed).
 *  - Step 8: failed production QA prevents VERIFIED.
 *  - Step 9: the report is rendered ONLY from evidence fields; missing values
 *    are printed as UNVERIFIED, never invented.
 *
 * Pure + deterministic (no I/O, network, or AI) so it is fully unit-testable.
 */

export const DEPLOYMENT_STATES = [
  'REPO_FROZEN',
  'CODE_CHANGED',
  'FILES_MODIFIED',
  'LOCAL_BUILD',
  'TESTS_PASSED',
  'COMMIT_CREATED',
  'PUSH_COMPLETED',
  'DEPLOY_STARTED',
  'DEPLOY_IN_PROGRESS',
  'DEPLOY_COMPLETED',
  'HEALTH_CHECK_OK',
  'PRODUCTION_VERIFIED',
] as const;

export type DeploymentMachineState = (typeof DEPLOYMENT_STATES)[number];

/**
 * Values that are NEVER valid inside an evidence field. A real deployment
 * report carries real tool output — these are unfilled template slots.
 */
export const FORBIDDEN_EVIDENCE_VALUES: readonly string[] = [
  'AUTO-GENERATED',
  'AUTO GENERATED',
  'AUTOGENERATED',
  'UNKNOWN',
  'PENDING',
  'PLACEHOLDER',
  'MOCK',
  'MOCKED',
  'NARRATIVE',
  'GENERATED',
  'SIMULATED',
  'ESTIMATED',
  'ASSUMED',
];

/** Whether a single evidence value is a forbidden template value. Pure. */
export function isForbiddenEvidenceValue(value: string | null | undefined): boolean {
  if (value === null || value === undefined) return false;
  const normalized = String(value).trim().replace(/^[[\s]+|[\]\s]+$/g, '').toUpperCase();
  if (normalized.length === 0) return false;
  return FORBIDDEN_EVIDENCE_VALUES.includes(normalized);
}

/**
 * Advance the deployment state machine by exactly one state. Skipping states
 * is a hard error — a deployment cannot claim PUSH_COMPLETED without
 * COMMIT_CREATED, or PRODUCTION_VERIFIED without HEALTH_CHECK_OK.
 * Pure — deterministic.
 */
export function advanceDeploymentState(
  current: DeploymentMachineState,
  next: DeploymentMachineState,
): { ok: boolean; error: string | null } {
  const currentIndex = DEPLOYMENT_STATES.indexOf(current);
  const nextIndex = DEPLOYMENT_STATES.indexOf(next);
  if (currentIndex === -1) return { ok: false, error: `unknown current state: ${current}` };
  if (nextIndex === -1) return { ok: false, error: `unknown next state: ${next}` };
  if (nextIndex !== currentIndex + 1) {
    return {
      ok: false,
      error: `illegal transition ${current} -> ${next}: states may not be skipped (expected ${DEPLOYMENT_STATES[currentIndex + 1] ?? 'none — already terminal'})`,
    };
  }
  return { ok: true, error: null };
}

/** The 18 required evidence fields (owner spec Step 6). */
export type DeploymentEvidenceReport = {
  repository: string | null;
  branch: string | null;
  commitSha: string | null;
  previousCommitSha: string | null;
  filesChanged: number | null;
  linesAdded: number | null;
  linesRemoved: number | null;
  pushStatus: string | null;
  deploymentPlatform: string | null;
  deploymentId: string | null;
  deploymentStatus: string | null;
  deploymentTimestamp: string | null;
  productionUrl: string | null;
  healthEndpoint: string | null;
  httpStatus: number | null;
  runningCommitSha: string | null;
  runtimeVersion: string | null;
  verificationTime: string | null;
  /** Step 8 — production QA verdict. null = QA not run (prevents VERIFIED). */
  qaResult: 'PASS' | 'FAIL' | null;
};

export type DeploymentValidationResult = {
  finalStatus: 'VERIFIED' | 'UNVERIFIED';
  missingFields: string[];
  forbiddenValues: string[];
  failures: string[];
};

const REQUIRED_FIELDS: readonly (keyof DeploymentEvidenceReport)[] = [
  'repository',
  'branch',
  'commitSha',
  'previousCommitSha',
  'filesChanged',
  'linesAdded',
  'linesRemoved',
  'pushStatus',
  'deploymentPlatform',
  'deploymentId',
  'deploymentStatus',
  'deploymentTimestamp',
  'productionUrl',
  'healthEndpoint',
  'httpStatus',
  'runningCommitSha',
  'runtimeVersion',
  'verificationTime',
];

/** Real git SHA: 7-40 hex chars. Pure. */
export function isRealCommitSha(value: string | null | undefined): boolean {
  if (!value) return false;
  return /^[0-9a-f]{7,40}$/i.test(String(value).trim());
}

/** Short/long SHA prefix equality — the commit-match rule (Step 7). Pure. */
export function commitShasMatch(a: string | null | undefined, b: string | null | undefined): boolean {
  if (!isRealCommitSha(a) || !isRealCommitSha(b)) return false;
  const left = String(a).trim().toLowerCase();
  const right = String(b).trim().toLowerCase();
  return left.startsWith(right) || right.startsWith(left);
}

/**
 * Validate a deployment evidence report. VERIFIED requires: every field
 * present, no forbidden template values, pushStatus completed, deployment
 * status live/succeeded, HTTP 200 health, running commit === GitHub commit,
 * and production QA PASS. Anything else is UNVERIFIED with explicit reasons.
 * Pure — deterministic.
 */
export function validateDeploymentEvidence(report: DeploymentEvidenceReport): DeploymentValidationResult {
  const missingFields: string[] = [];
  const forbiddenValues: string[] = [];
  const failures: string[] = [];

  for (const field of REQUIRED_FIELDS) {
    const value = report[field];
    if (value === null || value === undefined || String(value).trim().length === 0) {
      missingFields.push(field);
      continue;
    }
    if (typeof value === 'string' && isForbiddenEvidenceValue(value)) {
      forbiddenValues.push(`${field}=${String(value).trim()}`);
    }
  }

  if (!isRealCommitSha(report.commitSha) && report.commitSha !== null) {
    failures.push(`commitSha is not a real git SHA: ${report.commitSha}`);
  }
  if (!isRealCommitSha(report.runningCommitSha) && report.runningCommitSha !== null) {
    failures.push(`runningCommitSha is not a real git SHA: ${report.runningCommitSha}`);
  }
  if (report.httpStatus !== null && report.httpStatus !== 200) {
    failures.push(`health endpoint returned HTTP ${report.httpStatus} (200 required)`);
  }
  if (isRealCommitSha(report.commitSha) && isRealCommitSha(report.runningCommitSha)
    && !commitShasMatch(report.commitSha, report.runningCommitSha)) {
    failures.push(`running commit ${report.runningCommitSha} does not match GitHub commit ${report.commitSha}`);
  }
  if (report.pushStatus !== null && !/^(completed|pushed|success)$/i.test(report.pushStatus.trim())) {
    failures.push(`pushStatus is not a completed push: ${report.pushStatus}`);
  }
  if (report.deploymentStatus !== null && !/^(live|succeeded|success|deploy_succeeded)$/i.test(report.deploymentStatus.trim())) {
    failures.push(`deploymentStatus is not a completed deploy: ${report.deploymentStatus}`);
  }
  if (report.qaResult === null) {
    failures.push('production QA was not run');
  } else if (report.qaResult === 'FAIL') {
    failures.push('production QA failed');
  }

  const finalStatus: 'VERIFIED' | 'UNVERIFIED' =
    missingFields.length === 0 && forbiddenValues.length === 0 && failures.length === 0
      ? 'VERIFIED'
      : 'UNVERIFIED';

  return { finalStatus, missingFields, forbiddenValues, failures };
}

/**
 * Render the Step 9 final report — factual evidence only. Missing values are
 * printed as UNVERIFIED; nothing is ever invented to fill a slot.
 * Pure — deterministic.
 */
export function formatDeploymentReport(report: DeploymentEvidenceReport): string {
  const validation = validateDeploymentEvidence(report);
  const show = (value: string | number | null): string =>
    value === null || value === undefined || String(value).trim().length === 0
      ? 'UNVERIFIED'
      : String(value);

  const lines: string[] = [
    `Repository: ${show(report.repository)}`,
    `Branch: ${show(report.branch)}`,
    `Commit SHA: ${show(report.commitSha)}`,
    `Deployment Platform: ${show(report.deploymentPlatform)}`,
    `Deployment ID: ${show(report.deploymentId)}`,
    `Deployment Status: ${show(report.deploymentStatus)}`,
    `Deployment Timestamp: ${show(report.deploymentTimestamp)}`,
    `Production URL: ${show(report.productionUrl)}`,
    `Health URL: ${show(report.healthEndpoint)}`,
    `HTTP Status: ${show(report.httpStatus)}`,
    `Running Commit SHA: ${show(report.runningCommitSha)}`,
    `Runtime Version: ${show(report.runtimeVersion)}`,
    `QA Result: ${report.qaResult ?? 'UNVERIFIED'}`,
    '',
    `FINAL STATUS: ${validation.finalStatus}`,
  ];

  if (validation.finalStatus === 'UNVERIFIED') {
    const reasons = [
      ...validation.missingFields.map((f) => `missing evidence field: ${f}`),
      ...validation.forbiddenValues.map((v) => `forbidden evidence value: ${v}`),
      ...validation.failures,
    ];
    lines.push(`REASON = ${reasons.length > 0 ? reasons.join('; ') : 'Missing production evidence'}`);
  }

  return lines.join('\n');
}
