/**
 * IVX Self-Improvement System — Phase 5.
 *
 * Continuously evaluates platform performance and creates improvement tasks:
 *   - Failure analysis — root cause detection
 *   - Deployment incident review
 *   - Production issue tracking
 *   - Performance regression detection
 *   - User feedback integration
 *
 * Creates improvement tasks automatically and feeds them to the orchestrator.
 *
 * HARD HONESTY RULES:
 *   - Only reports real, observed failures/incidents.
 *   - Never fabricates issues to appear productive.
 *   - Each improvement task includes evidence of the problem.
 *   - Auto-created tasks are labeled as auto-generated.
 */
import { appendFile, mkdir, readFile, rename, writeFile } from 'node:fs/promises';
import path from 'node:path';

export const IVX_SELF_IMPROVEMENT_MARKER = 'ivx-self-improvement-2026-07-01';

// ── Types ──────────────────────────────────────────────────────────────────

export type ImprovementCategory =
  | 'failure_root_cause'
  | 'deployment_incident'
  | 'production_issue'
  | 'performance_regression'
  | 'user_feedback'
  | 'code_quality'
  | 'security_gap'
  | 'dependency_debt';

export type ImprovementSeverity = 'critical' | 'high' | 'medium' | 'low';

export type ImprovementTask = {
  id: string;
  category: ImprovementCategory;
  title: string;
  description: string;
  severity: ImprovementSeverity;
  evidence: string;
  detectedAt: string;
  autoGenerated: boolean;
  status: 'open' | 'in_progress' | 'resolved' | 'wont_fix';
  assignedAgent: string | null;
  resolution: string | null;
  resolvedAt: string | null;
};

export type SelfImprovementCycle = {
  id: string;
  startedAt: string;
  completedAt: string | null;
  categoriesEvaluated: ImprovementCategory[];
  issuesFound: number;
  tasksCreated: number;
  tasksResolved: number;
  summary: string;
};

export type SelfImprovementState = {
  marker: string;
  lastRunAt: string | null;
  nextRunAt: string | null;
  runCount: number;
  totalTasks: number;
  openTasks: number;
  tasks: ImprovementTask[];
  cycles: SelfImprovementCycle[];
  enabled: boolean;
};

// ── Durable State ──────────────────────────────────────────────────────────

const STATE_DIR = path.join(process.cwd(), 'logs', 'audit', 'self-improvement');
const STATE_FILE = path.join(STATE_DIR, 'state.json');
const TASKS_LOG = path.join(STATE_DIR, 'tasks.jsonl');

let _state: SelfImprovementState | null = null;

async function ensureDirs(): Promise<void> {
  await mkdir(STATE_DIR, { recursive: true });
}

function defaultState(): SelfImprovementState {
  return {
    marker: IVX_SELF_IMPROVEMENT_MARKER,
    lastRunAt: null,
    nextRunAt: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    runCount: 0,
    totalTasks: 0,
    openTasks: 0,
    tasks: [],
    cycles: [],
    enabled: true,
  };
}

async function loadState(): Promise<SelfImprovementState> {
  if (_state) return _state;
  await ensureDirs();
  try {
    const raw = await readFile(STATE_FILE, 'utf-8');
    const parsed = JSON.parse(raw) as SelfImprovementState;
    if (parsed.marker === IVX_SELF_IMPROVEMENT_MARKER) {
      _state = parsed;
      return _state;
    }
  } catch { /* first run */ }
  _state = defaultState();
  await persistState();
  return _state;
}

async function persistState(): Promise<void> {
  if (!_state) return;
  await ensureDirs();
  const tmp = STATE_FILE + '.tmp';
  await writeFile(tmp, JSON.stringify(_state, null, 2), 'utf-8');
  await rename(tmp, STATE_FILE);
}

// ── Core Logic ─────────────────────────────────────────────────────────────

/**
 * Create an improvement task from an observed issue.
 */
export async function createImprovementTask(
  category: ImprovementCategory,
  title: string,
  description: string,
  severity: ImprovementSeverity,
  evidence: string,
  autoGenerated: boolean = true,
): Promise<ImprovementTask> {
  const state = await loadState();
  const task: ImprovementTask = {
    id: `imp-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
    category,
    title,
    description,
    severity,
    evidence,
    detectedAt: new Date().toISOString(),
    autoGenerated,
    status: 'open',
    assignedAgent: null,
    resolution: null,
    resolvedAt: null,
  };

  state.tasks.unshift(task);
  state.totalTasks++;
  state.openTasks = state.tasks.filter((t) => t.status === 'open').length;
  await persistState();
  await appendFile(TASKS_LOG, JSON.stringify(task) + '\n', 'utf-8');
  return task;
}

/**
 * Resolve an improvement task.
 */
export async function resolveImprovementTask(
  taskId: string,
  resolution: string,
): Promise<ImprovementTask | null> {
  const state = await loadState();
  const task = state.tasks.find((t) => t.id === taskId);
  if (!task) return null;
  task.status = 'resolved';
  task.resolution = resolution;
  task.resolvedAt = new Date().toISOString();
  state.openTasks = state.tasks.filter((t) => t.status === 'open').length;
  await persistState();
  return task;
}

/**
 * Start a self-improvement cycle.
 */
export async function startImprovementCycle(): Promise<SelfImprovementCycle> {
  const cycle: SelfImprovementCycle = {
    id: `sic-${Date.now()}`,
    startedAt: new Date().toISOString(),
    completedAt: null,
    categoriesEvaluated: [],
    issuesFound: 0,
    tasksCreated: 0,
    tasksResolved: 0,
    summary: 'Cycle started — evaluating platform performance.',
  };
  return cycle;
}

/**
 * Complete a self-improvement cycle.
 */
export async function completeImprovementCycle(cycle: SelfImprovementCycle): Promise<SelfImprovementCycle> {
  const state = await loadState();
  cycle.completedAt = new Date().toISOString();
  cycle.summary = `Cycle complete: ${cycle.issuesFound} issues found, ${cycle.tasksCreated} tasks created, ${cycle.tasksResolved} tasks resolved.`;
  state.cycles.unshift(cycle);
  if (state.cycles.length > 30) state.cycles = state.cycles.slice(0, 30);
  state.lastRunAt = cycle.completedAt;
  state.nextRunAt = new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString();
  state.runCount++;
  await persistState();
  return cycle;
}

/**
 * Evaluate failures from the orchestrator and create improvement tasks.
 */
export async function evaluateOrchestratorFailures(
  failedTasks: Array<{ id: string; goal: string; error: string }>,
): Promise<ImprovementTask[]> {
  const tasks: ImprovementTask[] = [];
  for (const ft of failedTasks) {
    const task = await createImprovementTask(
      'failure_root_cause',
      `Orchestrator task failed: ${ft.goal.slice(0, 80)}`,
      `Task ${ft.id} failed with error: ${ft.error}. Root cause analysis needed.`,
      'medium',
      `Orchestrator failure record: ${ft.id}`,
    );
    tasks.push(task);
  }
  return tasks;
}

/**
 * Evaluate deployment incidents and create improvement tasks.
 */
export async function evaluateDeploymentIncident(
  incident: string,
  severity: ImprovementSeverity = 'high',
): Promise<ImprovementTask> {
  return createImprovementTask(
    'deployment_incident',
    'Deployment incident detected',
    incident,
    severity,
    'Deployment watchdog or health check',
  );
}

/**
 * Get the current self-improvement state.
 */
export async function getSelfImprovementState(): Promise<SelfImprovementState> {
  return loadState();
}

/**
 * Get open improvement tasks.
 */
export async function getOpenTasks(): Promise<ImprovementTask[]> {
  const state = await loadState();
  return state.tasks
    .filter((t) => t.status === 'open' || t.status === 'in_progress')
    .sort((a, b) => {
      const severityWeight: Record<ImprovementSeverity, number> = {
        critical: 4, high: 3, medium: 2, low: 1,
      };
      return severityWeight[b.severity] - severityWeight[a.severity];
    });
}

// ── Category Labels ────────────────────────────────────────────────────────

export const IMPROVEMENT_CATEGORY_LABELS: Record<ImprovementCategory, string> = {
  failure_root_cause: 'Failure Root Cause',
  deployment_incident: 'Deployment Incident',
  production_issue: 'Production Issue',
  performance_regression: 'Performance Regression',
  user_feedback: 'User Feedback',
  code_quality: 'Code Quality',
  security_gap: 'Security Gap',
  dependency_debt: 'Dependency Debt',
};

// ── Validation ─────────────────────────────────────────────────────────────

export async function validateSelfImprovement(): Promise<{ valid: boolean; issues: string[] }> {
  const state = await loadState();
  const issues: string[] = [];
  if (state.marker !== IVX_SELF_IMPROVEMENT_MARKER) issues.push('State marker mismatch');
  return { valid: issues.length === 0, issues };
}
