/**
 * IVX AUTONOMOUS CODER — REAL CODE-WRITING ENGINE.
 *
 * Owner mandate 2026-07-19: turn IVX IA from a routing system into a REAL
 * senior developer that can independently inspect, edit, test, revise, commit,
 * and verify real code changes without Rork authoring the patch.
 *
 * This engine runs a bounded engineering loop:
 *
 *   INSPECT → PLAN → PATCH → TEST → ANALYZE → REVISE → VERIFY → COMMIT →
 *   AWAIT_OWNER_APPROVAL → DEPLOY → PRODUCTION_VERIFY
 *
 * The LLM (owner-controlled, via ivx-ai-runtime.ts requestIVXAIText) generates
 * the patch. The engine applies it, runs real tests + typecheck, and if they
 * fail, feeds the error back to the LLM for revision (bounded to
 * maximumIterations). When tests pass, the engine commits via the GitHub Git
 * Data API (owner-controlled GITHUB_TOKEN). Deploy requires owner approval
 * (approvalPolicy: 'owner_gated') and uses render_trigger_deploy.
 *
 * NOTHING is faked. If the LLM fails to produce a valid patch, the engine
 * returns STATUS: BLOCKED with the exact failures. If tests fail after
 * maximumIterations, the engine returns STATUS: BLOCKED with the current diff
 * and failure output. A job is only marked COMPLETED when a real patch exists,
 * relevant tests passed, typecheck passed, and (for code changes) a real commit
 * SHA was produced.
 */
import { execFile } from 'node:child_process';
import { randomUUID } from 'node:crypto';
import { mkdir, readFile, readdir, stat, writeFile, rm } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { promisify } from 'node:util';
import { requestIVXAIText } from '../ivx-ai-runtime';

const execFileAsync = promisify(execFile);

export const IVX_AUTONOMOUS_CODER_MARKER = 'ivx-autonomous-coder-2026-07-19';

/** Bounded loop: max LLM revision iterations before BLOCKED. */
const MAX_ITERATIONS = 5;
/** Per-command timeout (ms). */
const COMMAND_TIMEOUT_MS = 60_000;
/** Max files to inspect per job. */
const MAX_INSPECTED_FILES = 30;
/** Max file preview chars sent to the LLM. */
const FILE_PREVIEW_CHARS = 3000;
/** Max stdout/stderr fed back to the LLM on revision. */
const FAILURE_OUTPUT_CHARS = 4000;

export type IVXAutonomousCoderExecutionMode = 'read_only' | 'code_change' | 'deploy';

export type IVXAutonomousCoderPatchOperation = {
  path: string;
  kind: 'replace_exact' | 'create_file';
  oldText: string;
  newText: string;
  reason: string;
};

export type IVXAutonomousCoderTestResult = {
  command: string;
  ok: boolean;
  exitCode: number | null;
  stdoutTail: string;
  stderrTail: string;
  durationMs: number;
};

export type IVXAutonomousCoderIteration = {
  iteration: number;
  patchGenerated: boolean;
  patchApplied: boolean;
  testsRun: boolean;
  testsPassed: boolean;
  typecheckRun: boolean;
  typecheckPassed: boolean;
  failureSummary: string | null;
  revised: boolean;
};

export type IVXAutonomousCoderProof = {
  marker: typeof IVX_AUTONOMOUS_CODER_MARKER;
  taskId: string;
  goal: string;
  executionMode: IVXAutonomousCoderExecutionMode;
  approvalPolicy: 'owner_gated';
  ownerId: string;
  startingSha: string | null;
  filesInspected: string[];
  rootCause: string;
  technicalPlan: string;
  iterations: IVXAutonomousCoderIteration[];
  finalPatch: IVXAutonomousCoderPatchOperation[];
  filesChanged: string[];
  commandsRun: IVXAutonomousCoderTestResult[];
  testsPassed: boolean;
  typecheckPassed: boolean;
  buildRun: boolean;
  commitSha: string | null;
  commitUrl: string | null;
  branch: string | null;
  deployApproved: boolean;
  deployId: string | null;
  deployStatus: string | null;
  productionVerified: boolean;
  liveCommit: string | null;
  healthOk: boolean;
  iterationCount: number;
  durationMs: number;
  finalStatus: 'COMPLETED' | 'BLOCKED' | 'FAILED';
  error: string | null;
  generatedAt: string;
  secretValuesReturned: false;
  /** The patch was generated by the IVX LLM, not by Rork manually editing. */
  patchAuthoredBy: 'ivx_llm' | 'ivx_deterministic_fallback' | null;
};

export type IVXAutonomousCoderInput = {
  taskId: string;
  goal: string;
  executionMode: IVXAutonomousCoderExecutionMode;
  ownerId: string;
  approvalPolicy: 'owner_gated';
  /** Owner approval to deploy (required when executionMode === 'deploy'). */
  deployApproved?: boolean;
  /** Owner approval confirmation text for deploy. */
  deployConfirmationText?: string;
  /** Injectable LLM caller for testing. */
  llmCaller?: (system: string, user: string) => Promise<string>;
  /** Injectable test runner for testing. */
  testRunner?: (cwd: string, command: string) => Promise<IVXAutonomousCoderTestResult>;
  /** Injectable commit function for testing. */
  commitFn?: (filePaths: string[], branch: string) => Promise<{ commitSha: string; commitUrl: string; branch: string }>;
  /** Injectable deploy function for testing. */
  deployFn?: (commitSha: string) => Promise<{ deployId: string | null; deployStatus: string | null }>;
  /** Injectable health checker for testing. */
  healthChecker?: () => Promise<{ ok: boolean; commit: string | null }>,
  /** Injectable project root for testing (defaults to the real repo root). */
  projectRoot?: string,
  /** Injectable file writer for testing (defaults to node:fs/promises writeFile). */
  fileWriter?: (relPath: string, content: string) => Promise<void>,
  /** Injectable file reader for testing. */
  fileReader?: (relPath: string) => Promise<string>,
  /** Injectable sleep function for deploy wait (defaults to 20s; tests pass 0). */
  sleepFn?: (ms: number) => Promise<void>,
  /** Phase callback for real-time stage updates. */
  onPhase?: (phase: IVXAutonomousCoderPhase, detail: string) => void,
};

export type IVXAutonomousCoderPhase =
  | 'queued'
  | 'inspecting'
  | 'planning'
  | 'patching'
  | 'testing'
  | 'analyzing'
  | 'revising'
  | 'verifying'
  | 'committing'
  | 'awaiting_owner_approval'
  | 'deploying'
  | 'production_verifying'
  | 'completed'
  | 'blocked'
  | 'failed';

function nowIso(): string {
  return new Date().toISOString();
}

function safeErrorMessage(error: unknown): string {
  return error instanceof Error ? error.message.slice(0, 800) : 'Unknown autonomous coder error.';
}

function truncate(value: string, max: number): string {
  if (value.length <= max) return value;
  return `${value.slice(0, max - 3)}...`;
}

const DEFAULT_PROJECT_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');

/** Resolve the project root for this run (injectable for tests). */
function resolveProjectRoot(input: IVXAutonomousCoderInput): string {
  return input.projectRoot ?? DEFAULT_PROJECT_ROOT;
}

// ── FILE INSPECTION ──────────────────────────────────────────────────────────

const INSPECT_IGNORED_DIRS = new Set([
  '.git', '.rork', 'node_modules', '.expo', 'dist', 'build', 'coverage',
  'logs', 'tmp', '__tests__', '__mocks__', 'mocks', '.github',
]);

const INSPECTABLE_EXTENSIONS = new Set([
  '.ts', '.tsx', '.js', '.jsx', '.mjs', '.json', '.md', '.yaml', '.yml',
]);

async function walkInspectableFiles(relDir: string, results: string[], max: number, projectRoot: string): Promise<void> {
  if (results.length >= max) return;
  const absDir = path.join(projectRoot, relDir);
  let entries: string[];
  try {
    entries = await readdir(absDir);
  } catch {
    return;
  }
  for (const entry of entries) {
    if (results.length >= max) return;
    const relEntry = relDir ? `${relDir}/${entry}` : entry;
    const absEntry = path.join(absDir, entry);
    let info;
    try {
      info = await stat(absEntry);
    } catch {
      continue;
    }
    if (info.isDirectory()) {
      if (INSPECT_IGNORED_DIRS.has(entry)) continue;
      if (!relDir && entry !== 'backend' && entry !== 'expo') continue;
      await walkInspectableFiles(relEntry, results, max, projectRoot);
    } else if (info.isFile()) {
      const ext = path.extname(entry);
      if (INSPECTABLE_EXTENSIONS.has(ext)) {
        results.push(relEntry);
      }
    }
  }
}

function pickInspectionTargets(goal: string, availableFiles: string[]): string[] {
  const alwaysInclude = [
    'backend/services/ivx-autonomous-coder-pilot.ts',
    'backend/services/ivx-senior-developer-worker.ts',
    'backend/services/ivx-senior-developer-runtime.ts',
    'backend/ivx-ai-runtime.ts',
    'backend/api/ivx-owner-ai.ts',
    'backend/hono.ts',
    'render.yaml',
    'package.json',
  ].filter((f) => availableFiles.includes(f));

  const words = Array.from(new Set(
    goal.toLowerCase()
      .replace(/[^a-z0-9\s]/g, ' ')
      .split(/\s+/)
      .filter((w) => w.length >= 4)
      .filter((w) => !['that', 'this', 'with', 'from', 'have', 'please', 'change', 'deploy', 'anything', 'current', 'status', 'label', 'version'].includes(w)),
  ));

  const hintMatches = availableFiles
    .filter((f) => words.some((w) => f.toLowerCase().includes(w)))
    .slice(0, 15);

  // Also include files whose CONTENT might contain the goal's significant terms.
  // This is handled in the inspect phase by reading file previews.

  return Array.from(new Set([...alwaysInclude, ...hintMatches])).slice(0, MAX_INSPECTED_FILES);
}

async function readFilePreview(relPath: string, projectRoot: string): Promise<{ path: string; content: string; bytes: number } | null> {
  try {
    const absPath = path.join(projectRoot, relPath);
    const content = await readFile(absPath, 'utf8');
    return {
      path: relPath,
      content: truncate(content, FILE_PREVIEW_CHARS),
      bytes: Buffer.byteLength(content, 'utf8'),
    };
  } catch {
    return null;
  }
}

// ── PATCH APPLICATION ────────────────────────────────────────────────────────

/** Paths the autonomous coder is allowed to modify. */
const ALLOWED_PATCH_PATHS = /^((?:backend|expo)\/[A-Za-z0-9_.\/-]+\.ts$|(?:backend|expo)\/[A-Za-z0-9_.\/-]+\.tsx$|expo\/[A-Za-z0-9_.\/-]+\.json$|expo\/[A-Za-z0-9_.\/-]+\.gradle$)/;

function assertSafePatchPath(filePath: string): void {
  if (filePath.includes('..') || filePath.startsWith('/')) {
    throw new Error(`Unsafe patch path rejected: ${filePath}`);
  }
  if (!ALLOWED_PATCH_PATHS.test(filePath)) {
    throw new Error(`Patch path outside allowed roots: ${filePath}. Only backend/*.ts, expo/*.ts(x), expo/*.json, expo/*.gradle are permitted.`);
  }
}

async function applyPatchOperation(
  op: IVXAutonomousCoderPatchOperation,
  projectRoot: string,
  fileWriter?: (relPath: string, content: string) => Promise<void>,
  fileReader?: (relPath: string) => Promise<string>,
): Promise<void> {
  assertSafePatchPath(op.path);
  const fullPath = path.join(projectRoot, op.path);
  const write = fileWriter ?? (async (rel: string, content: string) => {
    await mkdir(path.dirname(path.join(projectRoot, rel)), { recursive: true });
    await writeFile(path.join(projectRoot, rel), content, 'utf8');
  });
  const read = fileReader ?? (async (rel: string) => readFile(path.join(projectRoot, rel), 'utf8'));
  if (op.kind === 'create_file') {
    const { existsSync } = await import('node:fs');
    if (existsSync(fullPath)) {
      throw new Error(`Create-file target already exists: ${op.path}`);
    }
    await write(op.path, op.newText);
  } else {
    const source = await read(op.path);
    if (!source.includes(op.oldText)) {
      throw new Error(`Patch oldText not found in ${op.path}; cannot apply safely.`);
    }
    const updated = source.replace(op.oldText, op.newText);
    await write(op.path, updated);
  }
}

async function revertPatchOperation(
  op: IVXAutonomousCoderPatchOperation,
  projectRoot: string,
  fileWriter?: (relPath: string, content: string) => Promise<void>,
  fileReader?: (relPath: string) => Promise<string>,
): Promise<void> {
  const write = fileWriter ?? (async (rel: string, content: string) => {
    await mkdir(path.dirname(path.join(projectRoot, rel)), { recursive: true });
    await writeFile(path.join(projectRoot, rel), content, 'utf8');
  });
  const read = fileReader ?? (async (rel: string) => readFile(path.join(projectRoot, rel), 'utf8'));
  if (op.kind === 'create_file') {
    try { await rm(path.join(projectRoot, op.path)); } catch { /* already gone */ }
  } else {
    try {
      const source = await read(op.path);
      if (source.includes(op.newText)) {
        await write(op.path, source.replace(op.newText, op.oldText));
      }
    } catch { /* file may not exist */ }
  }
}

// ── TEST + TYPECHECK RUNNER ──────────────────────────────────────────────────

async function runCommand(cwd: string, command: string): Promise<IVXAutonomousCoderTestResult> {
  const started = Date.now();
  const parts = command.split(/\s+/);
  const cmd = parts[0];
  const args = parts.slice(1);
  try {
    const result = await execFileAsync(cmd, args, {
      cwd,
      timeout: COMMAND_TIMEOUT_MS,
      maxBuffer: 1024 * 1024 * 4,
      env: { ...process.env, CI: '1', FORCE_COLOR: '0' },
    });
    return {
      command,
      ok: true,
      exitCode: 0,
      stdoutTail: truncate(typeof result.stdout === 'string' ? result.stdout : '', 2000),
      stderrTail: truncate(typeof result.stderr === 'string' ? result.stderr : '', 2000),
      durationMs: Date.now() - started,
    };
  } catch (error) {
    const err = error as { code?: number; stdout?: string; stderr?: string; signal?: string };
    return {
      command,
      ok: false,
      exitCode: typeof err.code === 'number' ? err.code : null,
      stdoutTail: truncate(typeof err.stdout === 'string' ? err.stdout : '', 2000),
      stderrTail: truncate(typeof err.stderr === 'string' ? err.stderr : '', 2000),
      durationMs: Date.now() - started,
    };
  }
}

/** Pick the most relevant test file for the goal. */
function pickTargetTestFile(goal: string, changedFiles: string[]): string {
  // If a changed file has a corresponding .test.ts, run it.
  for (const changed of changedFiles) {
    const testFile = changed.replace(/\.ts$/, '.test.ts').replace(/^backend\//, 'backend/');
    if (testFile !== changed) {
      // Check if the test file path matches a known test pattern
      return testFile;
    }
  }
  // Default: run the autonomous coder's own tests
  return 'backend/ivx-autonomous-coder.test.ts';
}

// ── LLM PATCH GENERATION ─────────────────────────────────────────────────────

const PATCH_SYSTEM_PROMPT = `You are the IVX Autonomous Coder — a real senior developer engine.
Given a GOAL and FILE CONTENTS, generate a JSON patch to achieve the goal.

OUTPUT FORMAT (strict JSON, no markdown, no prose):
{
  "rootCause": "one-line root cause",
  "technicalPlan": "one-line plan",
  "operations": [
    {
      "path": "backend/services/example.ts",
      "kind": "replace_exact",
      "oldText": "the exact text to find",
      "newText": "the replacement text",
      "reason": "why this change"
    }
  ]
}

Rules:
- kind must be "replace_exact" (replace oldText with newText) or "create_file" (new file).
- oldText must be an EXACT substring of the file content (copy it verbatim).
- Make the smallest safe change.
- Only modify files under backend/ or expo/.
- No secrets, no destructive operations.`;

function buildPatchUserPrompt(goal: string, files: { path: string; content: string }[], failureContext: string | null): string {
  const fileBlocks = files.map((f) => `--- FILE: ${f.path} ---\n${f.content}`).join('\n\n');
  const failureBlock = failureContext
    ? `\n\n--- PREVIOUS ATTEMPT FAILED ---\n${failureContext}\n\nRevise the patch to fix the failure. Output the corrected JSON.`
    : '';
  return `GOAL:\n${goal}\n\nFILES:\n${fileBlocks}${failureBlock}`;
}

function parseLLMPatchResponse(response: string): { rootCause: string; technicalPlan: string; operations: IVXAutonomousCoderPatchOperation[] } | null {
  try {
    // Strip markdown code fences if present
    const cleaned = response.replace(/```json\s*/gi, '').replace(/```\s*/g, '').trim();
    // Find the first { and last }
    const start = cleaned.indexOf('{');
    const end = cleaned.lastIndexOf('}');
    if (start < 0 || end < 0 || end <= start) return null;
    const jsonStr = cleaned.slice(start, end + 1);
    const parsed = JSON.parse(jsonStr) as {
      rootCause?: string;
      technicalPlan?: string;
      operations?: Array<{
        path?: string;
        kind?: string;
        oldText?: string;
        newText?: string;
        reason?: string;
      }>;
    };
    if (!Array.isArray(parsed.operations)) return null;
    const operations: IVXAutonomousCoderPatchOperation[] = [];
    for (const op of parsed.operations) {
      if (typeof op.path !== 'string' || typeof op.kind !== 'string') continue;
      if (op.kind !== 'replace_exact' && op.kind !== 'create_file') continue;
      if (typeof op.oldText !== 'string' || typeof op.newText !== 'string') continue;
      operations.push({
        path: op.path,
        kind: op.kind,
        oldText: op.oldText,
        newText: op.newText,
        reason: typeof op.reason === 'string' ? op.reason : '',
      });
    }
    if (operations.length === 0) return null;
    return {
      rootCause: typeof parsed.rootCause === 'string' ? parsed.rootCause : 'LLM-generated patch',
      technicalPlan: typeof parsed.technicalPlan === 'string' ? parsed.technicalPlan : 'Replace exact text per operations',
      operations,
    };
  } catch {
    return null;
  }
}

async function callLLMForPatch(
  system: string,
  user: string,
  llmCaller?: (system: string, user: string) => Promise<string>,
): Promise<string> {
  if (llmCaller) return llmCaller(system, user);
  const result = await requestIVXAIText({
    module: 'ivx-autonomous-coder',
    requestId: `ac-${randomUUID()}`,
    system,
    prompt: user,
    maxOutputTokens: 4096,
  });
  return result.text;
}

// ── GITHUB COMMIT (Git Data API) ─────────────────────────────────────────────

const GITHUB_API_BASE_URL = 'https://api.github.com';
const GITHUB_DEFAULT_BRANCH = 'main';

function readEnv(name: string): string {
  return (typeof process.env[name] === 'string' ? process.env[name] : '').trim();
}

function parseGithubRepoUrl(value: string): { owner: string; repo: string } | null {
  const match = value.match(/github\.com[:/]([^/\s]+)\/([^/.\s]+)(?:\.git)?/i);
  if (!match?.[1] || !match[2]) return null;
  return { owner: match[1], repo: match[2] };
}

async function getStartingSha(): Promise<string | null> {
  const repoUrl = readEnv('GITHUB_REPO_URL');
  const token = readEnv('GITHUB_TOKEN');
  const repoInfo = parseGithubRepoUrl(repoUrl);
  if (!repoInfo || !token) return null;
  const branch = readEnv('GITHUB_DEFAULT_BRANCH') || GITHUB_DEFAULT_BRANCH;
  try {
    const res = await fetch(
      `${GITHUB_API_BASE_URL}/repos/${repoInfo.owner}/${repoInfo.repo}/git/ref/heads/${encodeURIComponent(branch)}`,
      {
        headers: {
          Authorization: `Bearer ${token}`,
          Accept: 'application/vnd.github+json',
        },
        signal: AbortSignal.timeout(10000),
      },
    );
    if (!res.ok) return null;
    const data = await res.json() as { object?: { sha?: string } };
    return data.object?.sha ?? null;
  } catch {
    return null;
  }
}

async function commitFilesViaGitDataApi(
  filePaths: string[],
  branch: string,
): Promise<{ commitSha: string; commitUrl: string; branch: string }> {
  const repoUrl = readEnv('GITHUB_REPO_URL');
  const token = readEnv('GITHUB_TOKEN');
  const repoInfo = parseGithubRepoUrl(repoUrl);
  if (!repoInfo) throw new Error('GITHUB_REPO_URL is missing or invalid.');
  if (!token) throw new Error('GITHUB_TOKEN is missing.');

  const headers = {
    Authorization: `Bearer ${token}`,
    Accept: 'application/vnd.github+json',
    'Content-Type': 'application/json',
  };

  // Read the branch ref
  const refRes = await fetch(
    `${GITHUB_API_BASE_URL}/repos/${repoInfo.owner}/${repoInfo.repo}/git/ref/heads/${encodeURIComponent(branch)}`,
    { headers, signal: AbortSignal.timeout(10000) },
  );
  if (!refRes.ok) throw new Error(`GitHub branch ref lookup failed: ${refRes.status}`);
  const refData = await refRes.json() as { object?: { sha?: string } };
  const baseCommitSha = refData.object?.sha;
  if (!baseCommitSha) throw new Error('GitHub branch ref did not include a commit SHA.');

  // Get the base commit's tree
  const commitRes = await fetch(
    `${GITHUB_API_BASE_URL}/repos/${repoInfo.owner}/${repoInfo.repo}/git/commits/${encodeURIComponent(baseCommitSha)}`,
    { headers, signal: AbortSignal.timeout(10000) },
  );
  if (!commitRes.ok) throw new Error(`GitHub base commit lookup failed: ${commitRes.status}`);
  const commitData = await commitRes.json() as { tree?: { sha?: string } };
  const baseTreeSha = commitData.tree?.sha;
  if (!baseTreeSha) throw new Error('GitHub base commit did not include a tree SHA.');

  // Create the new tree with the changed files
  const tree = await Promise.all(filePaths.map(async (repoPath) => ({
    path: repoPath,
    mode: '100644' as const,
    type: 'blob' as const,
    content: await readFile(path.join(DEFAULT_PROJECT_ROOT, repoPath), 'utf8'),
  })));

  const treeRes = await fetch(
    `${GITHUB_API_BASE_URL}/repos/${repoInfo.owner}/${repoInfo.repo}/git/trees`,
    {
      method: 'POST',
      headers,
      body: JSON.stringify({ base_tree: baseTreeSha, tree }),
      signal: AbortSignal.timeout(15000),
    },
  );
  if (!treeRes.ok) throw new Error(`GitHub tree creation failed: ${treeRes.status}`);
  const treeData = await treeRes.json() as { sha?: string };
  const newTreeSha = treeData.sha;
  if (!newTreeSha) throw new Error('GitHub tree creation did not return a tree SHA.');

  // Create the commit
  const newCommitRes = await fetch(
    `${GITHUB_API_BASE_URL}/repos/${repoInfo.owner}/${repoInfo.repo}/git/commits`,
    {
      method: 'POST',
      headers,
      body: JSON.stringify({
        message: `IVX autonomous coder: ${new Date().toISOString()}`,
        tree: newTreeSha,
        parents: [baseCommitSha],
      }),
      signal: AbortSignal.timeout(15000),
    },
  );
  if (!newCommitRes.ok) throw new Error(`GitHub commit creation failed: ${newCommitRes.status}`);
  const newCommitData = await newCommitRes.json() as { sha?: string };
  const commitSha = newCommitData.sha;
  if (!commitSha) throw new Error('GitHub commit creation did not return a commit SHA.');

  // Update the branch ref
  const updateRes = await fetch(
    `${GITHUB_API_BASE_URL}/repos/${repoInfo.owner}/${repoInfo.repo}/git/refs/heads/${encodeURIComponent(branch)}`,
    {
      method: 'PATCH',
      headers,
      body: JSON.stringify({ sha: commitSha, force: false }),
      signal: AbortSignal.timeout(10000),
    },
  );
  if (!updateRes.ok) throw new Error(`GitHub branch update failed: ${updateRes.status}`);

  return {
    commitSha,
    commitUrl: `https://github.com/${repoInfo.owner}/${repoInfo.repo}/commit/${commitSha}`,
    branch,
  };
}

// ── RENDER DEPLOY ────────────────────────────────────────────────────────────

async function triggerRenderDeploy(commitSha: string): Promise<{ deployId: string | null; deployStatus: string | null }> {
  const apiKey = readEnv('RENDER_API_KEY');
  const serviceId = readEnv('RENDER_SERVICE_ID');
  if (!apiKey || !serviceId) {
    throw new Error('RENDER_API_KEY or RENDER_SERVICE_ID is missing.');
  }
  const res = await fetch(`https://api.render.com/v1/services/${serviceId}/deploys`, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${apiKey}`,
      'Content-Type': 'application/json',
      Accept: 'application/json',
    },
    body: JSON.stringify({ commitId: commitSha }),
    signal: AbortSignal.timeout(15000),
  });
  if (!res.ok) {
    const body = await res.text().catch(() => '');
    throw new Error(`Render deploy trigger failed: ${res.status} ${body.slice(0, 300)}`);
  }
  const data = await res.json() as { id?: string; status?: string };
  return { deployId: data.id ?? null, deployStatus: data.status ?? 'triggered' };
}

// ── PRODUCTION HEALTH VERIFY ──────────────────────────────────────────────────

async function verifyProductionHealth(): Promise<{ ok: boolean; commit: string | null }> {
  const healthUrl = process.env.IVX_HEALTH_URL || 'https://api.ivxholding.com/health';
  try {
    const res = await fetch(healthUrl, { signal: AbortSignal.timeout(15000) });
    if (!res.ok) return { ok: false, commit: null };
    const data = await res.json() as { commitSha?: string; status?: string };
    return { ok: data.status === 'healthy', commit: data.commitSha ?? null };
  } catch {
    return { ok: false, commit: null };
  }
}

// ── MAIN ENGINE LOOP ─────────────────────────────────────────────────────────

export async function runIVXAutonomousCoder(input: IVXAutonomousCoderInput): Promise<IVXAutonomousCoderProof> {
  const startedAt = Date.now();
  const onPhase = input.onPhase;
  const iterations: IVXAutonomousCoderIteration[] = [];
  const commandsRun: IVXAutonomousCoderTestResult[] = [];
  let filesChanged: string[] = [];
  let finalPatch: IVXAutonomousCoderPatchOperation[] = [];
  let rootCause = '';
  let technicalPlan = '';
  let patchAuthoredBy: 'ivx_llm' | 'ivx_deterministic_fallback' | null = null;

  // ── INSPECT ──────────────────────────────────────────────────────────────
  onPhase?.('inspecting', 'Indexing repository + picking inspection targets.');
  const projectRoot = resolveProjectRoot(input);
  const availableFiles: string[] = [];
  await walkInspectableFiles('backend', availableFiles, 200, projectRoot);
  await walkInspectableFiles('expo', availableFiles, 200, projectRoot);
  const targetPaths = pickInspectionTargets(input.goal, availableFiles);
  const inspectedFiles: { path: string; content: string }[] = [];
  for (const target of targetPaths) {
    const preview = await readFilePreview(target, projectRoot);
    if (preview) {
      inspectedFiles.push({ path: preview.path, content: preview.content });
    }
  }
  onPhase?.('inspecting', `Inspected ${inspectedFiles.length} file(s).`);

  // ── STARTING SHA ─────────────────────────────────────────────────────────
  const startingSha = await getStartingSha();

  // ── BOUNDED LOOP: PLAN → PATCH → TEST → ANALYZE → REVISE ────────────────
  let testsPassed = false;
  let typecheckPassed = false;
  let buildRun = false;
  let lastFailureContext: string | null = null;
  let iterationCount = 0;
  let anyPatchApplied = false;
  let anyPatchGenerated = false;
  let lastPatchFailureReason: string | null = null;

  for (iterationCount = 1; iterationCount <= MAX_ITERATIONS; iterationCount += 1) {
    onPhase?.('planning', `Iteration ${iterationCount}: generating patch via IVX LLM.`);
    let llmResponse = '';
    try {
      llmResponse = await callLLMForPatch(
        PATCH_SYSTEM_PROMPT,
        buildPatchUserPrompt(input.goal, inspectedFiles, lastFailureContext),
        input.llmCaller,
      );
    } catch (error) {
      const iteration: IVXAutonomousCoderIteration = {
        iteration: iterationCount,
        patchGenerated: false,
        patchApplied: false,
        testsRun: false,
        testsPassed: false,
        typecheckRun: false,
        typecheckPassed: false,
        failureSummary: `LLM call failed: ${safeErrorMessage(error)}`,
        revised: false,
      };
      iterations.push(iteration);
      break;
    }

    const parsed = parseLLMPatchResponse(llmResponse);
    if (!parsed || parsed.operations.length === 0) {
      anyPatchGenerated = false;
      lastPatchFailureReason = 'LLM did not return valid JSON patch operations.';
      const iteration: IVXAutonomousCoderIteration = {
        iteration: iterationCount,
        patchGenerated: false,
        patchApplied: false,
        testsRun: false,
        testsPassed: false,
        typecheckRun: false,
        typecheckPassed: false,
        failureSummary: 'LLM did not return valid JSON patch operations.',
        revised: false,
      };
      iterations.push(iteration);
      lastFailureContext = `LLM response did not contain valid patch operations. Response: ${truncate(llmResponse, 1000)}`;
      onPhase?.('revising', `Iteration ${iterationCount}: no valid patch; requesting revision.`);
      continue;
    }

    rootCause = parsed.rootCause;
    technicalPlan = parsed.technicalPlan;
    patchAuthoredBy = 'ivx_llm';
    finalPatch = parsed.operations;
    anyPatchGenerated = true;

    // ── APPLY PATCH ──────────────────────────────────────────────────────
    onPhase?.('patching', `Iteration ${iterationCount}: applying ${parsed.operations.length} patch operation(s).`);
    let patchApplied = false;
    const appliedOps: IVXAutonomousCoderPatchOperation[] = [];
    let applyError: string | null = null;
    try {
      for (const op of parsed.operations) {
        await applyPatchOperation(op, projectRoot, input.fileWriter, input.fileReader);
        appliedOps.push(op);
      }
      patchApplied = true;
      anyPatchApplied = true;
      filesChanged = [...new Set(appliedOps.map((op) => op.path))];
    } catch (error) {
      applyError = safeErrorMessage(error);
      lastPatchFailureReason = `Patch application failed: ${applyError}`;
      // Revert any partially applied ops
      for (const op of appliedOps) {
        await revertPatchOperation(op, projectRoot, input.fileWriter, input.fileReader);
      }
      filesChanged = [];
    }

    if (!patchApplied) {
      const iteration: IVXAutonomousCoderIteration = {
        iteration: iterationCount,
        patchGenerated: true,
        patchApplied: false,
        testsRun: false,
        testsPassed: false,
        typecheckRun: false,
        typecheckPassed: false,
        failureSummary: `Patch application failed: ${applyError}`,
        revised: true,
      };
      iterations.push(iteration);
      lastFailureContext = `Patch could not be applied: ${applyError}. The oldText may not match the file content exactly. Re-read the file content and generate a corrected patch.`;
      onPhase?.('revising', `Iteration ${iterationCount}: patch failed; requesting revision.`);
      continue;
    }

    // ── TEST ─────────────────────────────────────────────────────────────
    onPhase?.('testing', `Iteration ${iterationCount}: running targeted tests + typecheck.`);
    const targetTest = pickTargetTestFile(input.goal, filesChanged);
    const testCmd = `bun test ${targetTest}`;
    const testResult = input.testRunner
      ? await input.testRunner(projectRoot, testCmd)
      : await runCommand(projectRoot, testCmd);
    commandsRun.push(testResult);
    testsPassed = testResult.ok;

    const typecheckCmd = 'bun x tsc --noEmit';
    const typecheckResult = input.testRunner
      ? await input.testRunner(projectRoot, typecheckCmd)
      : await runCommand(projectRoot, typecheckCmd);
    commandsRun.push(typecheckResult);
    typecheckPassed = typecheckResult.ok;
    buildRun = true;

    if (testsPassed && typecheckPassed) {
      const iteration: IVXAutonomousCoderIteration = {
        iteration: iterationCount,
        patchGenerated: true,
        patchApplied: true,
        testsRun: true,
        testsPassed: true,
        typecheckRun: true,
        typecheckPassed: true,
        failureSummary: null,
        revised: false,
      };
      iterations.push(iteration);
      onPhase?.('verifying', `Iteration ${iterationCount}: tests + typecheck PASSED.`);
      break;
    }

    // ── ANALYZE FAILURE ──────────────────────────────────────────────────
    onPhase?.('analyzing', `Iteration ${iterationCount}: tests or typecheck failed; analyzing.`);
    const failureParts: string[] = [];
    if (!testsPassed) {
      failureParts.push(`TEST FAILURE (${testCmd}):\nstdout: ${testResult.stdoutTail}\nstderr: ${testResult.stderrTail}`);
    }
    if (!typecheckPassed) {
      failureParts.push(`TYPECHECK FAILURE (${typecheckCmd}):\nstdout: ${typecheckResult.stdoutTail}\nstderr: ${typecheckResult.stderrTail}`);
    }
    const failureSummary = truncate(failureParts.join('\n\n'), 2000);
    lastFailureContext = truncate(failureParts.join('\n\n'), FAILURE_OUTPUT_CHARS);

    const iteration: IVXAutonomousCoderIteration = {
      iteration: iterationCount,
      patchGenerated: true,
      patchApplied: true,
      testsRun: true,
      testsPassed: false,
      typecheckRun: true,
      typecheckPassed: false,
      failureSummary,
      revised: iterationCount < MAX_ITERATIONS,
    };
    iterations.push(iteration);

    // ── REVERT + REVISE ──────────────────────────────────────────────────
    if (iterationCount < MAX_ITERATIONS) {
      onPhase?.('revising', `Iteration ${iterationCount}: reverting patch; requesting LLM revision.`);
      for (const op of appliedOps) {
        await revertPatchOperation(op, projectRoot, input.fileWriter, input.fileReader);
      }
      filesChanged = [];
      continue;
    }

    // Max iterations reached — BLOCKED
    onPhase?.('blocked', `Max iterations (${MAX_ITERATIONS}) reached; tests still failing.`);
    // Revert the last attempt
    for (const op of appliedOps) {
      await revertPatchOperation(op, projectRoot, input.fileWriter, input.fileReader);
    }
    filesChanged = [];
    break;
  }

  // ── VERIFY + COMMIT ──────────────────────────────────────────────────────
  let commitSha: string | null = null;
  let commitUrl: string | null = null;
  let branch: string | null = null;
  let deployId: string | null = null;
  let deployStatus: string | null = null;
  let productionVerified = false;
  let liveCommit: string | null = null;
  let healthOk = false;
  let finalStatus: 'COMPLETED' | 'BLOCKED' | 'FAILED' = 'BLOCKED';
  let error: string | null = null;

  if (testsPassed && typecheckPassed && filesChanged.length > 0) {
    // ── COMMIT ────────────────────────────────────────────────────────────
    if (input.executionMode === 'code_change' || input.executionMode === 'deploy') {
      onPhase?.('committing', 'Tests + typecheck passed; committing via GitHub Git Data API.');
      try {
        const branchName = readEnv('GITHUB_DEFAULT_BRANCH') || GITHUB_DEFAULT_BRANCH;
        const commitResult = input.commitFn
          ? await input.commitFn(filesChanged, branchName)
          : await commitFilesViaGitDataApi(filesChanged, branchName);
        commitSha = commitResult.commitSha;
        commitUrl = commitResult.commitUrl;
        branch = commitResult.branch;
        onPhase?.('committing', `Commit created: ${commitSha}`);
      } catch (err) {
        finalStatus = 'FAILED';
        error = `Commit failed: ${safeErrorMessage(err)}`;
        onPhase?.('failed', error);
      }
    }

    if (commitSha || input.executionMode === 'read_only') {
      finalStatus = 'COMPLETED';
    }

    // ── DEPLOY (owner-gated) ──────────────────────────────────────────────
    if (input.executionMode === 'deploy' && commitSha) {
      if (input.deployApproved && input.deployConfirmationText === 'CONFIRM_IVX_RENDER_DEPLOY') {
        onPhase?.('deploying', 'Owner approval verified; triggering Render deploy.');
        try {
          const deployResult = input.deployFn
            ? await input.deployFn(commitSha)
            : await triggerRenderDeploy(commitSha);
          deployId = deployResult.deployId;
          deployStatus = deployResult.deployStatus;
          onPhase?.('deploying', `Deploy triggered: ${deployId ?? deployStatus}`);

          // ── PRODUCTION VERIFY ────────────────────────────────────────────
          onPhase?.('production_verifying', 'Waiting for deploy + verifying production health.');
          // Bounded wait for the deploy to propagate (simplified: poll health)
          const sleep = input.sleepFn ?? ((ms: number) => new Promise<void>((resolve) => setTimeout(resolve, ms)));
          await sleep(20_000);
          const health = input.healthChecker
            ? await input.healthChecker()
            : await verifyProductionHealth();
          healthOk = health.ok;
          liveCommit = health.commit;
          productionVerified = healthOk && liveCommit === commitSha;
          if (productionVerified) {
            finalStatus = 'COMPLETED';
          } else {
            finalStatus = 'COMPLETED';
            error = `Deploy triggered but production verification inconclusive: healthOk=${healthOk}, liveCommit=${liveCommit}, expected=${commitSha}`;
          }
        } catch (err) {
          finalStatus = 'FAILED';
          error = `Deploy failed: ${safeErrorMessage(err)}`;
          onPhase?.('failed', error);
        }
      } else {
        onPhase?.('awaiting_owner_approval', 'Deploy requested but owner approval not verified. Blocking deploy.');
        finalStatus = 'COMPLETED';
        error = 'Commit created. Deploy BLOCKED: owner approval required (confirm=true, confirmText="CONFIRM_IVX_RENDER_DEPLOY").';
      }
    }
  } else if (!anyPatchApplied && !anyPatchGenerated) {
    finalStatus = 'BLOCKED';
    error = `No valid patch was generated after ${iterations.length} iteration(s). Last reason: ${lastPatchFailureReason ?? 'LLM did not produce valid operations'}`;
    onPhase?.('blocked', error);
  } else if (!anyPatchApplied && anyPatchGenerated) {
    finalStatus = 'BLOCKED';
    error = `No patch could be applied after ${iterations.length} iteration(s). Last reason: ${lastPatchFailureReason ?? 'patch application failed'}`;
    onPhase?.('blocked', error);
  } else if (!testsPassed || !typecheckPassed) {
    finalStatus = 'BLOCKED';
    error = `Tests or typecheck failed after ${iterations.length} iteration(s). No commit created. Last failure: ${lastFailureContext ?? 'unknown'}`;
    onPhase?.('blocked', error);
  } else {
    finalStatus = 'FAILED';
    error = 'Autonomous coder did not produce a passing patch.';
    onPhase?.('failed', error);
  }

  const proof: IVXAutonomousCoderProof = {
    marker: IVX_AUTONOMOUS_CODER_MARKER,
    taskId: input.taskId,
    goal: input.goal,
    executionMode: input.executionMode,
    approvalPolicy: input.approvalPolicy,
    ownerId: input.ownerId,
    startingSha,
    filesInspected: inspectedFiles.map((f) => f.path),
    rootCause,
    technicalPlan,
    iterations,
    finalPatch,
    filesChanged,
    commandsRun,
    testsPassed,
    typecheckPassed,
    buildRun,
    commitSha,
    commitUrl,
    branch,
    deployApproved: Boolean(input.deployApproved && input.deployConfirmationText === 'CONFIRM_IVX_RENDER_DEPLOY'),
    deployId,
    deployStatus,
    productionVerified,
    liveCommit,
    healthOk,
    iterationCount,
    durationMs: Date.now() - startedAt,
    finalStatus,
    error,
    generatedAt: nowIso(),
    secretValuesReturned: false,
    patchAuthoredBy,
  };

  if (finalStatus === 'COMPLETED') {
    onPhase?.('completed', `Autonomous coder job completed. Commit: ${commitSha ?? 'none'}`);
  }
  return proof;
}

// ── OWNER-MANDATED ANSWER FORMAT ─────────────────────────────────────────────

export function buildAutonomousCoderAnswer(proof: IVXAutonomousCoderProof): string {
  const filesChangedList = proof.filesChanged.length > 0
    ? proof.filesChanged.join('\n')
    : 'NONE';

  const commandsList = proof.commandsRun.length > 0
    ? proof.commandsRun.map((cmd) => {
        const status = cmd.ok ? 'PASS' : 'FAIL';
        return `$ ${cmd.command} → ${status} (exit ${cmd.exitCode ?? '?'}, ${cmd.durationMs}ms)`;
      }).join('\n')
    : 'NONE';

  const iterationsList = proof.iterations.length > 0
    ? proof.iterations.map((it) =>
        `Iteration ${it.iteration}: patchGenerated=${it.patchGenerated} patchApplied=${it.patchApplied} testsPassed=${it.testsPassed} typecheckPassed=${it.typecheckPassed}${it.failureSummary ? ` failure=${it.failureSummary.slice(0, 200)}` : ''}`,
      ).join('\n')
    : 'NONE';

  return [
    `TASK ID:\n${proof.taskId}`,
    `STATUS:\n${proof.finalStatus}`,
    `MODE:\n${proof.executionMode}`,
    `STARTING SHA:\n${proof.startingSha ?? 'unknown'}`,
    `FILES INSPECTED:\n${proof.filesInspected.length > 0 ? proof.filesInspected.join('\n') : 'NONE'}`,
    `ROOT CAUSE:\n${proof.rootCause || 'not identified'}`,
    `TECHNICAL PLAN:\n${proof.technicalPlan || 'not generated'}`,
    `ITERATIONS:\n${iterationsList}`,
    `FILES CHANGED:\n${filesChangedList}`,
    `COMMANDS RUN:\n${commandsList}`,
    `TESTS:\n${proof.testsPassed ? 'PASS' : 'FAIL'}`,
    `TYPECHECK:\n${proof.typecheckPassed ? 'PASS' : 'FAIL'}`,
    `COMMIT SHA:\n${proof.commitSha ?? 'NONE'}`,
    `COMMIT URL:\n${proof.commitUrl ?? 'NONE'}`,
    `DEPLOYMENT:\n${proof.deployId ? `deployId=${proof.deployId} status=${proof.deployStatus}` : 'NOT REQUESTED'}`,
    `PRODUCTION VERIFICATION:\n${proof.productionVerified ? 'VERIFIED' : 'NOT VERIFIED'}`,
    `ITERATION COUNT:\n${proof.iterationCount}`,
    `PATCH AUTHORED BY:\n${proof.patchAuthoredBy ?? 'NONE'}`,
    `DURATION:\n${proof.durationMs}ms`,
    `ERROR:\n${proof.error ?? 'NONE'}`,
  ].join('\n\n');
}
