import { randomUUID } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

/**
 * IVX Senior Developer — Generated Feature Registry.
 *
 * This is the durable, production-visible backing store for features that the
 * Senior Developer runtime builds "from scratch". Each build writes a real,
 * committed source file under `ivx-generated-features/<slug>.ts` AND appends an
 * entry to `registry.json`. The live routes in `backend/hono.ts` read this
 * registry, so every committed + deployed feature is immediately visible in
 * production at `/api/ivx/senior-developer/features` (and `/features/:slug`).
 *
 * This is what makes the proof real: a new file is created, a real commit SHA
 * is produced, Render redeploys, and the new feature becomes visible in prod.
 */

export const IVX_GENERATED_FEATURE_REGISTRY_MARKER = 'ivx-generated-feature-registry-v1';

export type IVXGeneratedFeature = {
  slug: string;
  title: string;
  goal: string;
  summary: string;
  sourceFile: string;
  createdAt: string;
  createdBy: string;
  marker: typeof IVX_GENERATED_FEATURE_REGISTRY_MARKER;
};

export type IVXGeneratedFeatureRegistry = {
  marker: typeof IVX_GENERATED_FEATURE_REGISTRY_MARKER;
  updatedAt: string;
  features: IVXGeneratedFeature[];
};

const FEATURES_DIR = path.join(path.dirname(fileURLToPath(import.meta.url)), 'ivx-generated-features');
const REGISTRY_PATH = path.join(FEATURES_DIR, 'registry.json');
const PROJECT_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');

function nowIso(): string {
  return new Date().toISOString();
}

function relativeFromRoot(filePath: string): string {
  return path.relative(PROJECT_ROOT, filePath).replace(/\\/g, '/');
}

function emptyRegistry(): IVXGeneratedFeatureRegistry {
  return { marker: IVX_GENERATED_FEATURE_REGISTRY_MARKER, updatedAt: nowIso(), features: [] };
}

function coerceFeature(value: unknown): IVXGeneratedFeature | null {
  if (!value || typeof value !== 'object' || Array.isArray(value)) return null;
  const record = value as Record<string, unknown>;
  const slug = typeof record.slug === 'string' ? record.slug : '';
  if (!slug) return null;
  return {
    slug,
    title: typeof record.title === 'string' ? record.title : slug,
    goal: typeof record.goal === 'string' ? record.goal : '',
    summary: typeof record.summary === 'string' ? record.summary : '',
    sourceFile: typeof record.sourceFile === 'string' ? record.sourceFile : '',
    createdAt: typeof record.createdAt === 'string' ? record.createdAt : '',
    createdBy: typeof record.createdBy === 'string' ? record.createdBy : 'ivx-senior-developer-runtime',
    marker: IVX_GENERATED_FEATURE_REGISTRY_MARKER,
  };
}

/** Reads the registry from disk, returning an empty registry if it does not exist yet. */
export async function readGeneratedFeatureRegistry(): Promise<IVXGeneratedFeatureRegistry> {
  try {
    const raw = await readFile(REGISTRY_PATH, 'utf8');
    const parsed = JSON.parse(raw) as unknown;
    if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) return emptyRegistry();
    const record = parsed as Record<string, unknown>;
    const features = Array.isArray(record.features)
      ? record.features.map(coerceFeature).filter((item): item is IVXGeneratedFeature => item !== null)
      : [];
    return { marker: IVX_GENERATED_FEATURE_REGISTRY_MARKER, updatedAt: typeof record.updatedAt === 'string' ? record.updatedAt : nowIso(), features };
  } catch {
    return emptyRegistry();
  }
}

export async function listGeneratedFeatures(): Promise<IVXGeneratedFeature[]> {
  const registry = await readGeneratedFeatureRegistry();
  return registry.features;
}

export async function getGeneratedFeature(slug: string): Promise<IVXGeneratedFeature | null> {
  const registry = await readGeneratedFeatureRegistry();
  return registry.features.find((feature) => feature.slug === slug) ?? null;
}

function slugify(input: string): string {
  const base = input
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 40);
  return base || 'feature';
}

function escapeForTemplate(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
}

function buildFeatureModuleSource(feature: IVXGeneratedFeature): string {
  return `// AUTO-GENERATED by the IVX Senior Developer runtime — do not edit by hand.
// This is a real, committed source file proving a feature was built from scratch.

export const featureSlug = ${JSON.stringify(feature.slug)} as const;

export const featureManifest = {
  slug: ${JSON.stringify(feature.slug)},
  title: ${JSON.stringify(feature.title)},
  goal: \`${escapeForTemplate(feature.goal)}\`,
  summary: \`${escapeForTemplate(feature.summary)}\`,
  createdAt: ${JSON.stringify(feature.createdAt)},
  createdBy: ${JSON.stringify(feature.createdBy)},
} as const;

export type GeneratedFeatureManifest = typeof featureManifest;

/** Returns the manifest for this generated feature. */
export function describeFeature(): GeneratedFeatureManifest {
  return featureManifest;
}
`;
}

export type IVXGeneratedFeatureBuildResult = {
  feature: IVXGeneratedFeature;
  changedFiles: string[];
  liveRoute: string;
  listRoute: string;
};

/**
 * Builds a brand-new feature from a goal: writes a real source file and appends
 * it to the registry. Returns the repo-relative changed file paths so the
 * Senior Developer runtime can commit + deploy them.
 */
export async function buildGeneratedFeatureFromGoal(goal: string, createdBy: string = 'ivx-senior-developer-runtime'): Promise<IVXGeneratedFeatureBuildResult> {
  const trimmedGoal = goal.trim();
  if (!trimmedGoal) throw new Error('A goal is required to build a new feature.');

  const shortId = randomUUID().split('-')[0];
  const slug = `${slugify(trimmedGoal)}-${shortId}`;
  const title = trimmedGoal.length > 80 ? `${trimmedGoal.slice(0, 77)}...` : trimmedGoal;
  const createdAt = nowIso();
  const sourceFileAbsolute = path.join(FEATURES_DIR, `${slug}.ts`);
  const feature: IVXGeneratedFeature = {
    slug,
    title,
    goal: trimmedGoal,
    summary: `Feature module generated from goal: ${title}`,
    sourceFile: relativeFromRoot(sourceFileAbsolute),
    createdAt,
    createdBy,
    marker: IVX_GENERATED_FEATURE_REGISTRY_MARKER,
  };

  await mkdir(FEATURES_DIR, { recursive: true });
  await writeFile(sourceFileAbsolute, buildFeatureModuleSource(feature), 'utf8');

  const registry = await readGeneratedFeatureRegistry();
  const features = [feature, ...registry.features.filter((existing) => existing.slug !== slug)].slice(0, 200);
  const nextRegistry: IVXGeneratedFeatureRegistry = {
    marker: IVX_GENERATED_FEATURE_REGISTRY_MARKER,
    updatedAt: createdAt,
    features,
  };
  await writeFile(REGISTRY_PATH, `${JSON.stringify(nextRegistry, null, 2)}\n`, 'utf8');

  return {
    feature,
    changedFiles: [relativeFromRoot(sourceFileAbsolute), relativeFromRoot(REGISTRY_PATH)],
    liveRoute: `/api/ivx/senior-developer/features/${slug}`,
    listRoute: '/api/ivx/senior-developer/features',
  };
}
