export interface Country {
  code: string;
  name: string;
  dialCode: string;
  taxIdLabel: string;
  taxIdPlaceholder: string;
  taxIdFormat?: string;
}

export const COUNTRIES: Country[] = [
  { code: 'AF', name: 'Afghanistan', dialCode: '+93', taxIdLabel: 'Tax ID Number', taxIdPlaceholder: 'Enter tax ID' },
  { code: 'AL', name: 'Albania', dialCode: '+355', taxIdLabel: 'NIPT', taxIdPlaceholder: 'Enter NIPT' },
  { code: 'DZ', name: 'Algeria', dialCode: '+213', taxIdLabel: 'NIF', taxIdPlaceholder: 'Enter NIF' },
  { code: 'AD', name: 'Andorra', dialCode: '+376', taxIdLabel: 'NRT', taxIdPlaceholder: 'Enter NRT' },
  { code: 'AO', name: 'Angola', dialCode: '+244', taxIdLabel: 'NIF', taxIdPlaceholder: 'Enter NIF' },
  { code: 'AG', name: 'Antigua and Barbuda', dialCode: '+1-268', taxIdLabel: 'TIN', taxIdPlaceholder: 'Enter TIN' },
  { code: 'AR', name: 'Argentina', dialCode: '+54', taxIdLabel: 'CUIT/CUIL', taxIdPlaceholder: 'XX-XXXXXXXX-X' },
  { code: 'AM', name: 'Armenia', dialCode: '+374', taxIdLabel: 'HVHH', taxIdPlaceholder: 'Enter HVHH' },
  { code: 'AU', name: 'Australia', dialCode: '+61', taxIdLabel: 'TFN', taxIdPlaceholder: 'XXX XXX XXX' },
  { code: 'AT', name: 'Austria', dialCode: '+43', taxIdLabel: 'UID', taxIdPlaceholder: 'ATU XXXXXXXX' },
  { code: 'AZ', name: 'Azerbaijan', dialCode: '+994', taxIdLabel: 'VÖEN', taxIdPlaceholder: 'Enter VÖEN' },
  { code: 'BS', name: 'Bahamas', dialCode: '+1-242', taxIdLabel: 'TIN', taxIdPlaceholder: 'Enter TIN' },
  { code: 'BH', name: 'Bahrain', dialCode: '+973', taxIdLabel: 'CR Number', taxIdPlaceholder: 'Enter CR Number' },
  { code: 'BD', name: 'Bangladesh', dialCode: '+880', taxIdLabel: 'TIN', taxIdPlaceholder: 'Enter TIN' },
  { code: 'BB', name: 'Barbados', dialCode: '+1-246', taxIdLabel: 'TIN', taxIdPlaceholder: 'Enter TIN' },
  { code: 'BY', name: 'Belarus', dialCode: '+375', taxIdLabel: 'UNP', taxIdPlaceholder: 'Enter UNP' },
  { code: 'BE', name: 'Belgium', dialCode: '+32', taxIdLabel: 'BTW/TVA', taxIdPlaceholder: 'BE XXXX.XXX.XXX' },
  { code: 'BZ', name: 'Belize', dialCode: '+501', taxIdLabel: 'TIN', taxIdPlaceholder: 'Enter TIN' },
  { code: 'BJ', name: 'Benin', dialCode: '+229', taxIdLabel: 'IFU', taxIdPlaceholder: 'Enter IFU' },
  { code: 'BT', name: 'Bhutan', dialCode: '+975', taxIdLabel: 'TIN', taxIdPlaceholder: 'Enter TIN' },
  { code: 'BO', name: 'Bolivia', dialCode: '+591', taxIdLabel: 'NIT', taxIdPlaceholder: 'Enter NIT' },
  { code: 'BA', name: 'Bosnia and Herzegovina', dialCode: '+387', taxIdLabel: 'PDV', taxIdPlaceholder: 'Enter PDV' },
  { code: 'BW', name: 'Botswana', dialCode: '+267', taxIdLabel: 'TIN', taxIdPlaceholder: 'Enter TIN' },
  { code: 'BR', name: 'Brazil', dialCode: '+55', taxIdLabel: 'CPF/CNPJ', taxIdPlaceholder: 'XXX.XXX.XXX-XX' },
  { code: 'BN', name: 'Brunei', dialCode: '+673', taxIdLabel: 'TIN', taxIdPlaceholder: 'Enter TIN' },
  { code: 'BG', name: 'Bulgaria', dialCode: '+359', taxIdLabel: 'EGN/EIK', taxIdPlaceholder: 'Enter EGN/EIK' },
  { code: 'BF', name: 'Burkina Faso', dialCode: '+226', taxIdLabel: 'IFU', taxIdPlaceholder: 'Enter IFU' },
  { code: 'BI', name: 'Burundi', dialCode: '+257', taxIdLabel: 'NIF', taxIdPlaceholder: 'Enter NIF' },
  { code: 'KH', name: 'Cambodia', dialCode: '+855', taxIdLabel: 'TIN', taxIdPlaceholder: 'Enter TIN' },
  { code: 'CM', name: 'Cameroon', dialCode: '+237', taxIdLabel: 'NIU', taxIdPlaceholder: 'Enter NIU' },
  { code: 'CA', name: 'Canada', dialCode: '+1', taxIdLabel: 'SIN', taxIdPlaceholder: 'XXX XXX XXX' },
  { code: 'CV', name: 'Cape Verde', dialCode: '+238', taxIdLabel: 'NIF', taxIdPlaceholder: 'Enter NIF' },
  { code: 'CF', name: 'Central African Republic', dialCode: '+236', taxIdLabel: 'NIF', taxIdPlaceholder: 'Enter NIF' },
  { code: 'TD', name: 'Chad', dialCode: '+235', taxIdLabel: 'NIF', taxIdPlaceholder: 'Enter NIF' },
  { code: 'CL', name: 'Chile', dialCode: '+56', taxIdLabel: 'RUT', taxIdPlaceholder: 'XX.XXX.XXX-X' },
  { code: 'CN', name: 'China', dialCode: '+86', taxIdLabel: 'ID Number', taxIdPlaceholder: 'Enter ID Number' },
  { code: 'CO', name: 'Colombia', dialCode: '+57', taxIdLabel: 'NIT/CC', taxIdPlaceholder: 'Enter NIT/CC' },
  { code: 'KM', name: 'Comoros', dialCode: '+269', taxIdLabel: 'NIF', taxIdPlaceholder: 'Enter NIF' },
  { code: 'CG', name: 'Congo', dialCode: '+242', taxIdLabel: 'NIF', taxIdPlaceholder: 'Enter NIF' },
  { code: 'CR', name: 'Costa Rica', dialCode: '+506', taxIdLabel: 'Cédula', taxIdPlaceholder: 'Enter Cédula' },
  { code: 'HR', name: 'Croatia', dialCode: '+385', taxIdLabel: 'OIB', taxIdPlaceholder: 'Enter OIB' },
  { code: 'CU', name: 'Cuba', dialCode: '+53', taxIdLabel: 'NIT', taxIdPlaceholder: 'Enter NIT' },
  { code: 'CY', name: 'Cyprus', dialCode: '+357', taxIdLabel: 'TIC', taxIdPlaceholder: 'Enter TIC' },
  { code: 'CZ', name: 'Czech Republic', dialCode: '+420', taxIdLabel: 'DIČ', taxIdPlaceholder: 'CZ XXXXXXXX' },
  { code: 'DK', name: 'Denmark', dialCode: '+45', taxIdLabel: 'CPR', taxIdPlaceholder: 'XXXXXX-XXXX' },
  { code: 'DJ', name: 'Djibouti', dialCode: '+253', taxIdLabel: 'NIF', taxIdPlaceholder: 'Enter NIF' },
  { code: 'DM', name: 'Dominica', dialCode: '+1-767', taxIdLabel: 'TIN', taxIdPlaceholder: 'Enter TIN' },
  { code: 'DO', name: 'Dominican Republic', dialCode: '+1-809', taxIdLabel: 'RNC/Cédula', taxIdPlaceholder: 'Enter RNC/Cédula' },
  { code: 'EC', name: 'Ecuador', dialCode: '+593', taxIdLabel: 'RUC/CI', taxIdPlaceholder: 'Enter RUC/CI' },
  { code: 'EG', name: 'Egypt', dialCode: '+20', taxIdLabel: 'Tax Card', taxIdPlaceholder: 'Enter Tax Card Number' },
  { code: 'SV', name: 'El Salvador', dialCode: '+503', taxIdLabel: 'NIT/DUI', taxIdPlaceholder: 'Enter NIT/DUI' },
  { code: 'GQ', name: 'Equatorial Guinea', dialCode: '+240', taxIdLabel: 'NIF', taxIdPlaceholder: 'Enter NIF' },
  { code: 'ER', name: 'Eritrea', dialCode: '+291', taxIdLabel: 'TIN', taxIdPlaceholder: 'Enter TIN' },
  { code: 'EE', name: 'Estonia', dialCode: '+372', taxIdLabel: 'Isikukood', taxIdPlaceholder: 'Enter Isikukood' },
  { code: 'ET', name: 'Ethiopia', dialCode: '+251', taxIdLabel: 'TIN', taxIdPlaceholder: 'Enter TIN' },
  { code: 'FJ', name: 'Fiji', dialCode: '+679', taxIdLabel: 'TIN', taxIdPlaceholder: 'Enter TIN' },
  { code: 'FI', name: 'Finland', dialCode: '+358', taxIdLabel: 'HETU', taxIdPlaceholder: 'XXXXXX-XXXX' },
  { code: 'FR', name: 'France', dialCode: '+33', taxIdLabel: 'NIF', taxIdPlaceholder: 'Enter NIF' },
  { code: 'GA', name: 'Gabon', dialCode: '+241', taxIdLabel: 'NIF', taxIdPlaceholder: 'Enter NIF' },
  { code: 'GM', name: 'Gambia', dialCode: '+220', taxIdLabel: 'TIN', taxIdPlaceholder: 'Enter TIN' },
  { code: 'GE', name: 'Georgia', dialCode: '+995', taxIdLabel: 'Personal Number', taxIdPlaceholder: 'Enter Personal Number' },
  { code: 'DE', name: 'Germany', dialCode: '+49', taxIdLabel: 'Steuer-ID', taxIdPlaceholder: 'XX XXX XXX XXX' },
  { code: 'GH', name: 'Ghana', dialCode: '+233', taxIdLabel: 'TIN', taxIdPlaceholder: 'Enter TIN' },
  { code: 'GR', name: 'Greece', dialCode: '+30', taxIdLabel: 'AFM', taxIdPlaceholder: 'Enter AFM' },
  { code: 'GD', name: 'Grenada', dialCode: '+1-473', taxIdLabel: 'TIN', taxIdPlaceholder: 'Enter TIN' },
  { code: 'GT', name: 'Guatemala', dialCode: '+502', taxIdLabel: 'NIT', taxIdPlaceholder: 'Enter NIT' },
  { code: 'GN', name: 'Guinea', dialCode: '+224', taxIdLabel: 'NIF', taxIdPlaceholder: 'Enter NIF' },
  { code: 'GW', name: 'Guinea-Bissau', dialCode: '+245', taxIdLabel: 'NIF', taxIdPlaceholder: 'Enter NIF' },
  { code: 'GY', name: 'Guyana', dialCode: '+592', taxIdLabel: 'TIN', taxIdPlaceholder: 'Enter TIN' },
  { code: 'HT', name: 'Haiti', dialCode: '+509', taxIdLabel: 'NIF', taxIdPlaceholder: 'Enter NIF' },
  { code: 'HN', name: 'Honduras', dialCode: '+504', taxIdLabel: 'RTN', taxIdPlaceholder: 'Enter RTN' },
  { code: 'HK', name: 'Hong Kong', dialCode: '+852', taxIdLabel: 'HKID', taxIdPlaceholder: 'Enter HKID' },
  { code: 'HU', name: 'Hungary', dialCode: '+36', taxIdLabel: 'Adószám', taxIdPlaceholder: 'Enter Adószám' },
  { code: 'IS', name: 'Iceland', dialCode: '+354', taxIdLabel: 'Kennitala', taxIdPlaceholder: 'Enter Kennitala' },
  { code: 'IN', name: 'India', dialCode: '+91', taxIdLabel: 'PAN', taxIdPlaceholder: 'XXXXX0000X' },
  { code: 'ID', name: 'Indonesia', dialCode: '+62', taxIdLabel: 'NPWP', taxIdPlaceholder: 'XX.XXX.XXX.X-XXX.XXX' },
  { code: 'IR', name: 'Iran', dialCode: '+98', taxIdLabel: 'National Code', taxIdPlaceholder: 'Enter National Code' },
  { code: 'IQ', name: 'Iraq', dialCode: '+964', taxIdLabel: 'TIN', taxIdPlaceholder: 'Enter TIN' },
  { code: 'IE', name: 'Ireland', dialCode: '+353', taxIdLabel: 'PPS Number', taxIdPlaceholder: 'XXXXXXXA' },
  { code: 'IL', name: 'Israel', dialCode: '+972', taxIdLabel: 'Mispar Zehut', taxIdPlaceholder: 'Enter Mispar Zehut' },
  { code: 'IT', name: 'Italy', dialCode: '+39', taxIdLabel: 'Codice Fiscale', taxIdPlaceholder: 'XXXXXX00X00X000X' },
  { code: 'CI', name: 'Ivory Coast', dialCode: '+225', taxIdLabel: 'NIF', taxIdPlaceholder: 'Enter NIF' },
  { code: 'JM', name: 'Jamaica', dialCode: '+1-876', taxIdLabel: 'TRN', taxIdPlaceholder: 'Enter TRN' },
  { code: 'JP', name: 'Japan', dialCode: '+81', taxIdLabel: 'My Number', taxIdPlaceholder: 'Enter My Number' },
  { code: 'JO', name: 'Jordan', dialCode: '+962', taxIdLabel: 'National Number', taxIdPlaceholder: 'Enter National Number' },
  { code: 'KZ', name: 'Kazakhstan', dialCode: '+7', taxIdLabel: 'IIN', taxIdPlaceholder: 'Enter IIN' },
  { code: 'KE', name: 'Kenya', dialCode: '+254', taxIdLabel: 'PIN', taxIdPlaceholder: 'Enter PIN' },
  { code: 'KI', name: 'Kiribati', dialCode: '+686', taxIdLabel: 'TIN', taxIdPlaceholder: 'Enter TIN' },
  { code: 'KW', name: 'Kuwait', dialCode: '+965', taxIdLabel: 'Civil ID', taxIdPlaceholder: 'Enter Civil ID' },
  { code: 'KG', name: 'Kyrgyzstan', dialCode: '+996', taxIdLabel: 'INN', taxIdPlaceholder: 'Enter INN' },
  { code: 'LA', name: 'Laos', dialCode: '+856', taxIdLabel: 'TIN', taxIdPlaceholder: 'Enter TIN' },
  { code: 'LV', name: 'Latvia', dialCode: '+371', taxIdLabel: 'Personas kods', taxIdPlaceholder: 'Enter Personas kods' },
  { code: 'LB', name: 'Lebanon', dialCode: '+961', taxIdLabel: 'Fiscal Number', taxIdPlaceholder: 'Enter Fiscal Number' },
  { code: 'LS', name: 'Lesotho', dialCode: '+266', taxIdLabel: 'TIN', taxIdPlaceholder: 'Enter TIN' },
  { code: 'LR', name: 'Liberia', dialCode: '+231', taxIdLabel: 'TIN', taxIdPlaceholder: 'Enter TIN' },
  { code: 'LY', name: 'Libya', dialCode: '+218', taxIdLabel: 'TIN', taxIdPlaceholder: 'Enter TIN' },
  { code: 'LI', name: 'Liechtenstein', dialCode: '+423', taxIdLabel: 'PEID', taxIdPlaceholder: 'Enter PEID' },
  { code: 'LT', name: 'Lithuania', dialCode: '+370', taxIdLabel: 'Asmens kodas', taxIdPlaceholder: 'Enter Asmens kodas' },
  { code: 'LU', name: 'Luxembourg', dialCode: '+352', taxIdLabel: 'Matricule', taxIdPlaceholder: 'Enter Matricule' },
  { code: 'MO', name: 'Macau', dialCode: '+853', taxIdLabel: 'BIR', taxIdPlaceholder: 'Enter BIR' },
  { code: 'MK', name: 'North Macedonia', dialCode: '+389', taxIdLabel: 'EMBG', taxIdPlaceholder: 'Enter EMBG' },
  { code: 'MG', name: 'Madagascar', dialCode: '+261', taxIdLabel: 'NIF', taxIdPlaceholder: 'Enter NIF' },
  { code: 'MW', name: 'Malawi', dialCode: '+265', taxIdLabel: 'TPIN', taxIdPlaceholder: 'Enter TPIN' },
  { code: 'MY', name: 'Malaysia', dialCode: '+60', taxIdLabel: 'NRIC/TIN', taxIdPlaceholder: 'Enter NRIC/TIN' },
  { code: 'MV', name: 'Maldives', dialCode: '+960', taxIdLabel: 'TIN', taxIdPlaceholder: 'Enter TIN' },
  { code: 'ML', name: 'Mali', dialCode: '+223', taxIdLabel: 'NIF', taxIdPlaceholder: 'Enter NIF' },
  { code: 'MT', name: 'Malta', dialCode: '+356', taxIdLabel: 'ID Card', taxIdPlaceholder: 'Enter ID Card Number' },
  { code: 'MH', name: 'Marshall Islands', dialCode: '+692', taxIdLabel: 'TIN', taxIdPlaceholder: 'Enter TIN' },
  { code: 'MR', name: 'Mauritania', dialCode: '+222', taxIdLabel: 'NIF', taxIdPlaceholder: 'Enter NIF' },
  { code: 'MU', name: 'Mauritius', dialCode: '+230', taxIdLabel: 'NIC', taxIdPlaceholder: 'Enter NIC' },
  { code: 'MX', name: 'Mexico', dialCode: '+52', taxIdLabel: 'RFC/CURP', taxIdPlaceholder: 'Enter RFC/CURP' },
  { code: 'FM', name: 'Micronesia', dialCode: '+691', taxIdLabel: 'TIN', taxIdPlaceholder: 'Enter TIN' },
  { code: 'MD', name: 'Moldova', dialCode: '+373', taxIdLabel: 'IDNP', taxIdPlaceholder: 'Enter IDNP' },
  { code: 'MC', name: 'Monaco', dialCode: '+377', taxIdLabel: 'NIF', taxIdPlaceholder: 'Enter NIF' },
  { code: 'MN', name: 'Mongolia', dialCode: '+976', taxIdLabel: 'Register Number', taxIdPlaceholder: 'Enter Register Number' },
  { code: 'ME', name: 'Montenegro', dialCode: '+382', taxIdLabel: 'JMBG', taxIdPlaceholder: 'Enter JMBG' },
  { code: 'MA', name: 'Morocco', dialCode: '+212', taxIdLabel: 'ICE', taxIdPlaceholder: 'Enter ICE' },
  { code: 'MZ', name: 'Mozambique', dialCode: '+258', taxIdLabel: 'NUIT', taxIdPlaceholder: 'Enter NUIT' },
  { code: 'MM', name: 'Myanmar', dialCode: '+95', taxIdLabel: 'NRC', taxIdPlaceholder: 'Enter NRC' },
  { code: 'NA', name: 'Namibia', dialCode: '+264', taxIdLabel: 'TIN', taxIdPlaceholder: 'Enter TIN' },
  { code: 'NR', name: 'Nauru', dialCode: '+674', taxIdLabel: 'TIN', taxIdPlaceholder: 'Enter TIN' },
  { code: 'NP', name: 'Nepal', dialCode: '+977', taxIdLabel: 'PAN', taxIdPlaceholder: 'Enter PAN' },
  { code: 'NL', name: 'Netherlands', dialCode: '+31', taxIdLabel: 'BSN', taxIdPlaceholder: 'Enter BSN' },
  { code: 'NZ', name: 'New Zealand', dialCode: '+64', taxIdLabel: 'IRD Number', taxIdPlaceholder: 'XXX-XXX-XXX' },
  { code: 'NI', name: 'Nicaragua', dialCode: '+505', taxIdLabel: 'RUC', taxIdPlaceholder: 'Enter RUC' },
  { code: 'NE', name: 'Niger', dialCode: '+227', taxIdLabel: 'NIF', taxIdPlaceholder: 'Enter NIF' },
  { code: 'NG', name: 'Nigeria', dialCode: '+234', taxIdLabel: 'TIN', taxIdPlaceholder: 'Enter TIN' },
  { code: 'KP', name: 'North Korea', dialCode: '+850', taxIdLabel: 'ID Number', taxIdPlaceholder: 'Enter ID Number' },
  { code: 'NO', name: 'Norway', dialCode: '+47', taxIdLabel: 'Fødselsnummer', taxIdPlaceholder: 'XXXXXXXXXXX' },
  { code: 'OM', name: 'Oman', dialCode: '+968', taxIdLabel: 'Civil ID', taxIdPlaceholder: 'Enter Civil ID' },
  { code: 'PK', name: 'Pakistan', dialCode: '+92', taxIdLabel: 'CNIC/NTN', taxIdPlaceholder: 'Enter CNIC/NTN' },
  { code: 'PW', name: 'Palau', dialCode: '+680', taxIdLabel: 'TIN', taxIdPlaceholder: 'Enter TIN' },
  { code: 'PS', name: 'Palestine', dialCode: '+970', taxIdLabel: 'ID Number', taxIdPlaceholder: 'Enter ID Number' },
  { code: 'PA', name: 'Panama', dialCode: '+507', taxIdLabel: 'RUC/Cédula', taxIdPlaceholder: 'Enter RUC/Cédula' },
  { code: 'PG', name: 'Papua New Guinea', dialCode: '+675', taxIdLabel: 'TIN', taxIdPlaceholder: 'Enter TIN' },
  { code: 'PY', name: 'Paraguay', dialCode: '+595', taxIdLabel: 'RUC/CI', taxIdPlaceholder: 'Enter RUC/CI' },
  { code: 'PE', name: 'Peru', dialCode: '+51', taxIdLabel: 'RUC/DNI', taxIdPlaceholder: 'Enter RUC/DNI' },
  { code: 'PH', name: 'Philippines', dialCode: '+63', taxIdLabel: 'TIN', taxIdPlaceholder: 'XXX-XXX-XXX-XXX' },
  { code: 'PL', name: 'Poland', dialCode: '+48', taxIdLabel: 'PESEL/NIP', taxIdPlaceholder: 'Enter PESEL/NIP' },
  { code: 'PT', name: 'Portugal', dialCode: '+351', taxIdLabel: 'NIF', taxIdPlaceholder: 'Enter NIF' },
  { code: 'PR', name: 'Puerto Rico', dialCode: '+1-787', taxIdLabel: 'SSN', taxIdPlaceholder: 'XXX-XX-XXXX' },
  { code: 'QA', name: 'Qatar', dialCode: '+974', taxIdLabel: 'QID', taxIdPlaceholder: 'Enter QID' },
  { code: 'RO', name: 'Romania', dialCode: '+40', taxIdLabel: 'CNP', taxIdPlaceholder: 'Enter CNP' },
  { code: 'RU', name: 'Russia', dialCode: '+7', taxIdLabel: 'INN', taxIdPlaceholder: 'Enter INN' },
  { code: 'RW', name: 'Rwanda', dialCode: '+250', taxIdLabel: 'TIN', taxIdPlaceholder: 'Enter TIN' },
  { code: 'KN', name: 'Saint Kitts and Nevis', dialCode: '+1-869', taxIdLabel: 'TIN', taxIdPlaceholder: 'Enter TIN' },
  { code: 'LC', name: 'Saint Lucia', dialCode: '+1-758', taxIdLabel: 'TIN', taxIdPlaceholder: 'Enter TIN' },
  { code: 'VC', name: 'Saint Vincent and the Grenadines', dialCode: '+1-784', taxIdLabel: 'TIN', taxIdPlaceholder: 'Enter TIN' },
  { code: 'WS', name: 'Samoa', dialCode: '+685', taxIdLabel: 'TIN', taxIdPlaceholder: 'Enter TIN' },
  { code: 'SM', name: 'San Marino', dialCode: '+378', taxIdLabel: 'COE', taxIdPlaceholder: 'Enter COE' },
  { code: 'ST', name: 'Sao Tome and Principe', dialCode: '+239', taxIdLabel: 'NIF', taxIdPlaceholder: 'Enter NIF' },
  { code: 'SA', name: 'Saudi Arabia', dialCode: '+966', taxIdLabel: 'Iqama/National ID', taxIdPlaceholder: 'Enter Iqama/National ID' },
  { code: 'SN', name: 'Senegal', dialCode: '+221', taxIdLabel: 'NINEA', taxIdPlaceholder: 'Enter NINEA' },
  { code: 'RS', name: 'Serbia', dialCode: '+381', taxIdLabel: 'JMBG', taxIdPlaceholder: 'Enter JMBG' },
  { code: 'SC', name: 'Seychelles', dialCode: '+248', taxIdLabel: 'NIN', taxIdPlaceholder: 'Enter NIN' },
  { code: 'SL', name: 'Sierra Leone', dialCode: '+232', taxIdLabel: 'TIN', taxIdPlaceholder: 'Enter TIN' },
  { code: 'SG', name: 'Singapore', dialCode: '+65', taxIdLabel: 'NRIC/FIN', taxIdPlaceholder: 'Enter NRIC/FIN' },
  { code: 'SK', name: 'Slovakia', dialCode: '+421', taxIdLabel: 'Rodné číslo', taxIdPlaceholder: 'Enter Rodné číslo' },
  { code: 'SI', name: 'Slovenia', dialCode: '+386', taxIdLabel: 'EMŠO', taxIdPlaceholder: 'Enter EMŠO' },
  { code: 'SB', name: 'Solomon Islands', dialCode: '+677', taxIdLabel: 'TIN', taxIdPlaceholder: 'Enter TIN' },
  { code: 'SO', name: 'Somalia', dialCode: '+252', taxIdLabel: 'TIN', taxIdPlaceholder: 'Enter TIN' },
  { code: 'ZA', name: 'South Africa', dialCode: '+27', taxIdLabel: 'ID Number', taxIdPlaceholder: 'Enter ID Number' },
  { code: 'KR', name: 'South Korea', dialCode: '+82', taxIdLabel: 'RRN', taxIdPlaceholder: 'Enter RRN' },
  { code: 'SS', name: 'South Sudan', dialCode: '+211', taxIdLabel: 'TIN', taxIdPlaceholder: 'Enter TIN' },
  { code: 'ES', name: 'Spain', dialCode: '+34', taxIdLabel: 'DNI/NIE', taxIdPlaceholder: 'Enter DNI/NIE' },
  { code: 'LK', name: 'Sri Lanka', dialCode: '+94', taxIdLabel: 'NIC', taxIdPlaceholder: 'Enter NIC' },
  { code: 'SD', name: 'Sudan', dialCode: '+249', taxIdLabel: 'TIN', taxIdPlaceholder: 'Enter TIN' },
  { code: 'SR', name: 'Suriname', dialCode: '+597', taxIdLabel: 'ID Number', taxIdPlaceholder: 'Enter ID Number' },
  { code: 'SZ', name: 'Eswatini', dialCode: '+268', taxIdLabel: 'TIN', taxIdPlaceholder: 'Enter TIN' },
  { code: 'SE', name: 'Sweden', dialCode: '+46', taxIdLabel: 'Personnummer', taxIdPlaceholder: 'YYYYMMDD-XXXX' },
  { code: 'CH', name: 'Switzerland', dialCode: '+41', taxIdLabel: 'AHV-Nr', taxIdPlaceholder: 'XXX.XXXX.XXXX.XX' },
  { code: 'SY', name: 'Syria', dialCode: '+963', taxIdLabel: 'National ID', taxIdPlaceholder: 'Enter National ID' },
  { code: 'TW', name: 'Taiwan', dialCode: '+886', taxIdLabel: 'ID Number', taxIdPlaceholder: 'Enter ID Number' },
  { code: 'TJ', name: 'Tajikistan', dialCode: '+992', taxIdLabel: 'INN', taxIdPlaceholder: 'Enter INN' },
  { code: 'TZ', name: 'Tanzania', dialCode: '+255', taxIdLabel: 'TIN', taxIdPlaceholder: 'Enter TIN' },
  { code: 'TH', name: 'Thailand', dialCode: '+66', taxIdLabel: 'ID Card', taxIdPlaceholder: 'Enter ID Card Number' },
  { code: 'TL', name: 'Timor-Leste', dialCode: '+670', taxIdLabel: 'TIN', taxIdPlaceholder: 'Enter TIN' },
  { code: 'TG', name: 'Togo', dialCode: '+228', taxIdLabel: 'NIF', taxIdPlaceholder: 'Enter NIF' },
  { code: 'TO', name: 'Tonga', dialCode: '+676', taxIdLabel: 'TIN', taxIdPlaceholder: 'Enter TIN' },
  { code: 'TT', name: 'Trinidad and Tobago', dialCode: '+1-868', taxIdLabel: 'BIR Number', taxIdPlaceholder: 'Enter BIR Number' },
  { code: 'TN', name: 'Tunisia', dialCode: '+216', taxIdLabel: 'CIN', taxIdPlaceholder: 'Enter CIN' },
  { code: 'TR', name: 'Turkey', dialCode: '+90', taxIdLabel: 'TC Kimlik No', taxIdPlaceholder: 'Enter TC Kimlik No' },
  { code: 'TM', name: 'Turkmenistan', dialCode: '+993', taxIdLabel: 'Passport Number', taxIdPlaceholder: 'Enter Passport Number' },
  { code: 'TV', name: 'Tuvalu', dialCode: '+688', taxIdLabel: 'TIN', taxIdPlaceholder: 'Enter TIN' },
  { code: 'UG', name: 'Uganda', dialCode: '+256', taxIdLabel: 'TIN', taxIdPlaceholder: 'Enter TIN' },
  { code: 'UA', name: 'Ukraine', dialCode: '+380', taxIdLabel: 'РНОКПП', taxIdPlaceholder: 'Enter РНОКПП' },
  { code: 'AE', name: 'United Arab Emirates', dialCode: '+971', taxIdLabel: 'Emirates ID', taxIdPlaceholder: 'XXX-XXXX-XXXXXXX-X' },
  { code: 'GB', name: 'United Kingdom', dialCode: '+44', taxIdLabel: 'NI Number', taxIdPlaceholder: 'XX XXXXXX X' },
  { code: 'US', name: 'United States', dialCode: '+1', taxIdLabel: 'SSN', taxIdPlaceholder: 'XXX-XX-XXXX' },
  { code: 'UY', name: 'Uruguay', dialCode: '+598', taxIdLabel: 'RUT/CI', taxIdPlaceholder: 'Enter RUT/CI' },
  { code: 'UZ', name: 'Uzbekistan', dialCode: '+998', taxIdLabel: 'INN', taxIdPlaceholder: 'Enter INN' },
  { code: 'VU', name: 'Vanuatu', dialCode: '+678', taxIdLabel: 'TIN', taxIdPlaceholder: 'Enter TIN' },
  { code: 'VA', name: 'Vatican City', dialCode: '+379', taxIdLabel: 'Passport Number', taxIdPlaceholder: 'Enter Passport Number' },
  { code: 'VE', name: 'Venezuela', dialCode: '+58', taxIdLabel: 'RIF/CI', taxIdPlaceholder: 'Enter RIF/CI' },
  { code: 'VN', name: 'Vietnam', dialCode: '+84', taxIdLabel: 'CCCD/MST', taxIdPlaceholder: 'Enter CCCD/MST' },
  { code: 'YE', name: 'Yemen', dialCode: '+967', taxIdLabel: 'National ID', taxIdPlaceholder: 'Enter National ID' },
  { code: 'ZM', name: 'Zambia', dialCode: '+260', taxIdLabel: 'TPIN', taxIdPlaceholder: 'Enter TPIN' },
  { code: 'ZW', name: 'Zimbabwe', dialCode: '+263', taxIdLabel: 'ID Number', taxIdPlaceholder: 'Enter ID Number' },
];

export const getCountryByCode = (code: string): Country | undefined => {
  return COUNTRIES.find(c => c.code === code);
};

export const getCountryByName = (name: string): Country | undefined => {
  return COUNTRIES.find(c => c.name.toLowerCase() === name.toLowerCase());
};
