name = "ivx-render-origin-router"
main = "./ivx-render-origin-worker.js"
compatibility_date = "2026-05-06"
workers_dev = false

[[routes]]
pattern = "api.ivxholding.com/*"
zone_name = "ivxholding.com"

[[routes]]
pattern = "chat.ivxholding.com/*"
zone_name = "ivxholding.com"

[vars]
IVX_WORKER_USE_RESOLVE_OVERRIDE = "false"
