// AUTO-GENERATED by the IVX Senior Developer runtime — do not edit by hand.
// This is a real, committed source file proving a feature was built from scratch.

export const featureSlug = "apply-this-exact-two-file-production-har-cc3e0af5" as const;

export const featureManifest = {
  slug: "apply-this-exact-two-file-production-har-cc3e0af5",
  title: "Apply this EXACT two-file production hardening patch to the AI runtime (emerg...",
  goal: `Apply this EXACT two-file production hardening patch to the AI runtime (emergency gateway repair, 2026-07-18). Do not change any other files. Do not redesign — apply precisely these edits:

FILE 1: backend/services/ivx-provider-state-machine.ts
1. Add module-level state after the \`state\` const declarations:
   let failureLatchedAtMs: number | null = null;
   const RECOVERY_COOLDOWN_MS = parsed from env IVX_AI_PROVIDER_RECOVERY_COOLDOWN_MS, default 60000 (validate finite > 0).
2. In markProviderFailed(): set failureLatchedAtMs = Date.now() when latching PROVIDER_FAILED.
3. In markAIUnavailable(): set failureLatchedAtMs = Date.now() when latching AI_UNAVAILABLE.
4. In markProviderReady() and markFallbackReady(): set failureLatchedAtMs = null.
5. In resetProviderStateMachine(): set failureLatchedAtMs = null.
6. Rewrite shouldTryPrimary() to: return true when state is not PROVIDER_FAILED and not AI_UNAVAILABLE; return false when state.credentialLoaded is false; if failureLatchedAtMs !== null and Date.now() - failureLatchedAtMs >= RECOVERY_COOLDOWN_MS then set state.state = 'PROVIDER_VALIDATING', set failureLatchedAtMs = null, log a recovery message, and return true; otherwise return false. This converts the permanent AI_UNAVAILABLE latch (root cause of the 2026-07-18 outage) into a half-open circuit breaker with cooldown recovery.

FILE 2: backend/ivx-ai-runtime.ts
1. Change the first import from \`import { generateText, streamText, createGateway } from 'ai';\` to \`import { generateText, streamText } from 'ai';\` (remove createGateway - Vercel AI Gateway SDK dependency removed).
2. In requestIVXAIText primary attempt block: replace \`const gatewayProvider = isVercelKey ? createGateway({ apiKey }) : createOpenAI({ apiKey, baseURL });\` with \`const gatewayProvider = createOpenAI({ apiKey, baseURL });\` — the direct OpenAI-compatible client is used for BOTH key types with the key passed explicitly (baseURL already auto-selects https://api.openai.com/v1 for sk- keys and https://ai-gateway.vercel.sh/v1 for vck_ keys). Keep isVercelKey only for the markProviderReady provider-name argument.
3. Wrap the primary attempt in a bounded retry loop: const MAX_PRIMARY_ATTEMPTS = 3; retry ONLY when classifyProviderFailure(error) is one of 'network' | 'server_error' | 'rate_limit' AND the failure is not auth (401/403); between attempts await an exponential backoff sleep of 600ms * 2^(attempt-1). Never retry auth failures — keep the existing markProviderFailed call for them and break.
4. In streamIVXAIText: replace the same \`isVercelKey ? createGateway({ apiKey }) : createOpenAI({ apiKey, baseURL })\` conditional with \`const gatewayProvider = createOpenAI({ apiKey, baseURL });\`.
5. In ensureIVXAIGatewayEnvironment(): remove the env-var bridging block that sets process.env.AI_GATEWAY_API_KEY (keep the missing-key throw).
6. Add in-flight idempotency deduplication: a module-level \`const inFlightAIRequests = new Map<string, Promise<IVXAITextResult>>();\` and make requestIVXAIText dedupe by key \`\${module}::\${requestId}\` when requestId is present — concurrent duplicates return the same promise; the map entry is deleted when the promise settles.

VALIDATION: run typecheck; the existing backend/tests/ivx-provider-state-machine.test.ts must still pass unchanged (cooldown default 60s means immediate shouldTryPrimary checks after failure still return false).`,
  summary: `Feature module generated from goal: Apply this EXACT two-file production hardening patch to the AI runtime (emerg...`,
  createdAt: "2026-07-18T11:40:51.218Z",
  createdBy: "senior-developer:ivx-senior-dev-b5dc8caa-7d28-4ecb-9abe-f476faf83f20",
} as const;

export type GeneratedFeatureManifest = typeof featureManifest;

/** Returns the manifest for this generated feature. */
export function describeFeature(): GeneratedFeatureManifest {
  return featureManifest;
}
