export type QCSeverity = 'info' | 'warning' | 'critical' | 'fatal';
export type QCFlowId =
  | 'admin_publish_deal'
  | 'user_invest'
  | 'realtime_sync'
  | 'photo_protection'
  | 'trash_recovery'
  | 'storage_isolation'
  | 'chat_room'
  | 'analytics_rpc'
  | 'storage_upload'
  | 'auth_session';

export type QCModuleId =
  | 'supabase_db'
  | 'supabase_auth'
  | 'supabase_realtime'
  | 'supabase_storage'
  | 'chat_engine'
  | 'analytics_engine'
  | 'auth_engine'
  | 'upload_engine'
  | 'deal_engine'
  | 'photo_engine';

export type QCProbeStatus = 'pass' | 'warn' | 'fail' | 'skip';
export type QCHealAction =
  | 'retry_rpc'
  | 'reconnect_realtime'
  | 'invalidate_cache'
  | 'refresh_room_snapshot'
  | 'recover_network'
  | 'switch_fallback'
  | 'rerun_health_probe'
  | 'transition_stuck_sends'
  | 'resubscribe_channel'
  | 'clear_stale_cache';

export type QCHealSafety = 'safe' | 'requires_approval';

export type QCRepairTaskStatus = 'open' | 'in_progress' | 'awaiting_approval' | 'resolved' | 'dismissed';

export interface QCDiagnosticEvent {
  id: string;
  correlationId: string;
  timestamp: string;
  flow: QCFlowId;
  module: QCModuleId;
  severity: QCSeverity;
  title: string;
  summary: string;
  failingStep: string;
  likelyFile?: string;
  environment: string;
  metadata?: Record<string, string | number | boolean>;
  autoHealEligible: boolean;
  suggestedHealAction?: QCHealAction;
}

export interface QCProbeResult {
  probeId: string;
  flow: QCFlowId;
  module: QCModuleId;
  status: QCProbeStatus;
  latencyMs: number;
  message: string;
  details?: string;
  timestamp: string;
  diagnosticEvents: QCDiagnosticEvent[];
}

export interface QCHealAttempt {
  id: string;
  action: QCHealAction;
  safety: QCHealSafety;
  triggeredBy: string;
  correlationId: string;
  success: boolean;
  message: string;
  timestamp: string;
  durationMs: number;
}

export interface QCRepairTask {
  id: string;
  status: QCRepairTaskStatus;
  flow: QCFlowId;
  module: QCModuleId;
  severity: QCSeverity;
  title: string;
  description: string;
  likelyFiles: string[];
  suggestedFix: string;
  failureCount: number;
  firstSeenAt: string;
  lastSeenAt: string;
  diagnosticEventIds: string[];
  autoGenerated: boolean;
}

export interface QCAuditCycleResult {
  cycleId: string;
  startedAt: string;
  completedAt: string;
  durationMs: number;
  probeResults: QCProbeResult[];
  healAttempts: QCHealAttempt[];
  newRepairTasks: QCRepairTask[];
  summary: QCAuditSummary;
}

export interface QCAuditSummary {
  totalProbes: number;
  passed: number;
  warned: number;
  failed: number;
  skipped: number;
  healsAttempted: number;
  healsSucceeded: number;
  newTasksCreated: number;
  overallHealth: 'healthy' | 'degraded' | 'critical';
}

export interface QCDashboardSnapshot {
  lastCycleResult: QCAuditCycleResult | null;
  openRepairTasks: QCRepairTask[];
  recentHealAttempts: QCHealAttempt[];
  recentDiagnosticEvents: QCDiagnosticEvent[];
  monitoringActive: boolean;
  cycleIntervalMs: number;
  lastCycleAt: string | null;
  nextCycleAt: string | null;
}

export const FLOW_LABELS: Record<QCFlowId, string> = {
  admin_publish_deal: 'Admin Publishes Deal',
  user_invest: 'User Invests in Deal',
  realtime_sync: 'Realtime Sync',
  photo_protection: 'Photo Protection Flow',
  trash_recovery: 'Trash & Recovery Flow',
  storage_isolation: 'Project Storage Isolation',
  chat_room: 'Chat Room Lifecycle',
  analytics_rpc: 'Analytics RPC Health',
  storage_upload: 'Storage/Upload Health',
  auth_session: 'Auth/Session Health',
};

export const MODULE_LABELS: Record<QCModuleId, string> = {
  supabase_db: 'Supabase DB',
  supabase_auth: 'Supabase Auth',
  supabase_realtime: 'Supabase Realtime',
  supabase_storage: 'Supabase Storage',
  chat_engine: 'Chat Engine',
  analytics_engine: 'Analytics Engine',
  auth_engine: 'Auth Engine',
  upload_engine: 'Upload Engine',
  deal_engine: 'Deal Engine',
  photo_engine: 'Photo Engine',
};
