import { Platform, Alert } from 'react-native';

interface PDFExportOptions {
  html: string;
  fileName?: string;
}

export async function generateAndSharePDF(options: PDFExportOptions): Promise<boolean> {
  const { html, fileName = 'document' } = options;

  try {
    if (Platform.OS === 'web') {
      const printWindow = window.open('', '_blank');
      if (printWindow) {
        printWindow.document.write(html);
        printWindow.document.close();
        printWindow.print();
        return true;
      }
      return false;
    }

    const Print = await import('expo-print');
    const result = await Print.printToFileAsync({ html });
    console.log('[PDF] Generated at:', result.uri);

    const Sharing = await import('expo-sharing');
    const isAvailable = await Sharing.isAvailableAsync();
    if (isAvailable) {
      await Sharing.shareAsync(result.uri, {
        mimeType: 'application/pdf',
        dialogTitle: `Share ${fileName}`,
        UTI: 'com.adobe.pdf',
      });
      return true;
    } else {
      Alert.alert('PDF Generated', 'PDF was created but sharing is not available on this device.');
      return true;
    }
  } catch (error) {
    console.error('[PDF] Export error:', (error as Error)?.message);
    Alert.alert('Export Failed', 'Could not generate PDF. Please try again.');
    return false;
  }
}

export function buildContractHTML(data: {
  title: string;
  parties: string[];
  sections: { heading: string; content: string }[];
  date: string;
  footer?: string;
}): string {
  const sectionsHTML = data.sections.map((s, i) => `
    <div style="margin-bottom: 20px;">
      <h3 style="color: #333; font-size: 14px; margin-bottom: 8px;">${i + 1}. ${s.heading}</h3>
      <p style="color: #555; font-size: 12px; line-height: 1.6;">${s.content}</p>
    </div>
  `).join('');

  const partiesHTML = data.parties.map(p => `<li style="margin-bottom: 4px;">${p}</li>`).join('');

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <style>
        body { font-family: 'Helvetica Neue', Arial, sans-serif; padding: 40px; color: #333; max-width: 800px; margin: 0 auto; }
        .header { text-align: center; border-bottom: 2px solid #FFD700; padding-bottom: 20px; margin-bottom: 30px; }
        .header h1 { font-size: 22px; color: #111; margin: 0; }
        .header p { font-size: 12px; color: #888; margin-top: 8px; }
        .parties { background: #f9f9f9; padding: 16px; border-radius: 8px; margin-bottom: 24px; }
        .parties h3 { font-size: 14px; margin: 0 0 8px; }
        .parties ul { margin: 0; padding-left: 20px; }
        .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; font-size: 10px; color: #999; text-align: center; }
        .signature { margin-top: 60px; display: flex; justify-content: space-between; }
        .signature-line { border-top: 1px solid #333; width: 200px; padding-top: 8px; font-size: 11px; }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>${data.title}</h1>
        <p>Date: ${data.date} | IVX Holdings LLC</p>
      </div>
      <div class="parties">
        <h3>Parties:</h3>
        <ul>${partiesHTML}</ul>
      </div>
      ${sectionsHTML}
      <div class="signature">
        <div class="signature-line">Authorized Representative</div>
        <div class="signature-line">Counterparty</div>
      </div>
      <div class="footer">${data.footer || 'Generated by IVX Holdings LLC. This document is legally binding upon execution by all parties.'}</div>
    </body>
    </html>
  `;
}

export function buildDataExportHTML(data: {
  title: string;
  headers: string[];
  rows: string[][];
  generatedAt: string;
}): string {
  const headersHTML = data.headers.map(h => `<th style="padding: 8px 12px; text-align: left; border-bottom: 2px solid #FFD700; font-size: 12px;">${h}</th>`).join('');
  const rowsHTML = data.rows.map(row =>
    `<tr>${row.map(cell => `<td style="padding: 6px 12px; border-bottom: 1px solid #eee; font-size: 11px;">${cell}</td>`).join('')}</tr>`
  ).join('');

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <style>
        body { font-family: Arial, sans-serif; padding: 20px; }
        h1 { font-size: 18px; color: #111; }
        table { width: 100%; border-collapse: collapse; margin-top: 16px; }
        .meta { font-size: 11px; color: #888; margin-top: 4px; }
      </style>
    </head>
    <body>
      <h1>${data.title}</h1>
      <p class="meta">Generated: ${data.generatedAt} | IVX Holdings LLC</p>
      <table>
        <thead><tr>${headersHTML}</tr></thead>
        <tbody>${rowsHTML}</tbody>
      </table>
    </body>
    </html>
  `;
}
